// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Client  *OrderClientAnyOf  `json:"client,omitempty"`
	Address *OrderAddressAnyOf `json:"address,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type Verification struct {
	Verifier *string `json:"verifier,omitempty"`
}

func (v Verification) Validate() error {
	return schemaTypesValidate.Struct(v)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type OrderClientAnyOf struct {
	runtime.Either[Identity, Verification]
}

func (o *OrderClientAnyOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderClientAnyOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}

type OrderAddressAnyOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the OrderAddressAnyOf as bytes
func (o *OrderAddressAnyOf) Raw() json.RawMessage {
	return o.union
}

// AsString returns the union data inside the OrderAddressAnyOf as a string
func (o *OrderAddressAnyOf) AsString() (string, error) {
	return UnmarshalAs[string](o.union)
}

// FromString overwrites any union data inside the OrderAddressAnyOf as the provided string
func (o *OrderAddressAnyOf) FromString(v string) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

func (o OrderAddressAnyOf) MarshalJSON() ([]byte, error) {
	bts, err := o.union.MarshalJSON()

	return bts, err
}

func (o *OrderAddressAnyOf) UnmarshalJSON(bts []byte) error {
	err := o.union.UnmarshalJSON(bts)

	return err
}
