// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Client  *Order_Client  `json:"client,omitempty"`
	Address *Order_Address `json:"address,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type Order_Client struct {
	Order_Client_AnyOf *Order_Client_AnyOf `json:"-"`
}

func (o Order_Client) Validate() error {
	return schemaTypesValidate.Struct(o)
}

func (o Order_Client) MarshalJSON() ([]byte, error) {
	// Collect each branch as an object JSON ({} if nil/null).
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Client_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Client_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Client) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		// keep zero value (all branches nil)
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("JSON object expected, got %s", string(trim))
	}

	if o.Order_Client_AnyOf == nil {
		o.Order_Client_AnyOf = &Order_Client_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Client_AnyOf); err != nil {
		return fmt.Errorf("Order_Client_AnyOf unmarshal: %w", err)
	}

	return nil
}

type Order_Address struct {
	Order_Address_AnyOf *Order_Address_AnyOf `json:"-"`
}

func (o Order_Address) Validate() error {
	return schemaTypesValidate.Struct(o)
}

func (o Order_Address) MarshalJSON() ([]byte, error) {
	// Collect each branch as an object JSON ({} if nil/null).
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Address_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Address_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Address) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		// keep zero value (all branches nil)
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("JSON object expected, got %s", string(trim))
	}

	if o.Order_Address_AnyOf == nil {
		o.Order_Address_AnyOf = &Order_Address_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Address_AnyOf); err != nil {
		return fmt.Errorf("Order_Address_AnyOf unmarshal: %w", err)
	}

	return nil
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type Verification struct {
	Verifier *string `json:"verifier,omitempty"`
}

func (v Verification) Validate() error {
	return schemaTypesValidate.Struct(v)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Order_Client_AnyOf struct {
	runtime.Either[Identity, Verification]
}

type Order_Address_AnyOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the Order_Address_AnyOf as bytes
func (o *Order_Address_AnyOf) Raw() json.RawMessage {
	return o.union
}

// AsString returns the union data inside the Order_Address_AnyOf as a string
func (o *Order_Address_AnyOf) AsString() (string, error) {
	return UnmarshalAs[string](o.union)
}

// FromString overwrites any union data inside the Order_Address_AnyOf as the provided string
func (o *Order_Address_AnyOf) FromString(v string) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

func (o Order_Address_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := o.union.MarshalJSON()

	return bts, err
}

func (o *Order_Address_AnyOf) UnmarshalJSON(bts []byte) error {
	err := o.union.UnmarshalJSON(bts)

	return err
}
