// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error)
}

func (c *Client) GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/files",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetFilesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetFilesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/files")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

type GetFilesResponse []GetFiles_Response

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type VariantA struct {
	A *string `json:"a,omitempty"`
}

func (v VariantA) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type VariantB struct {
	B *string `json:"b,omitempty"`
}

func (v VariantB) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type VariantC struct {
	C *string `json:"c,omitempty"`
}

func (v VariantC) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type GetFiles_Response struct {
	GetFiles_Response_OneOf *GetFiles_Response_OneOf `json:"-"`
}

func (g GetFiles_Response) Validate() error {
	return schemaTypesValidate.Struct(g)
}

func (g GetFiles_Response) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetFiles_Response_OneOf)
		if err != nil {
			return nil, fmt.Errorf("GetFiles_Response_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetFiles_Response) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetFiles_Response_OneOf == nil {
		g.GetFiles_Response_OneOf = &GetFiles_Response_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetFiles_Response_OneOf); err != nil {
		return fmt.Errorf("GetFiles_Response_OneOf unmarshal: %w", err)
	}

	return nil
}

type GetFiles_Response_OneOf_0 struct {
	A *string `json:"a,omitempty"`
	B *string `json:"b,omitempty"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type GetFiles_Response_OneOf struct {
	runtime.Either[GetFiles_Response_OneOf_0, VariantC]
}
