openapi: 3.0.0
info:
  title: API
  description: An example of `oneOf` schema in responses
  version: 1.0.0

paths:
  /service/gateway:
    post:
      summary: Process payment operations
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    Payload:
      oneOf:
        - $ref: '#/components/schemas/PayloadA'
        - $ref: '#/components/schemas/PayloadB'
        - $ref: '#/components/schemas/PayloadC'
    PayloadA:
      type: object
      properties:
        a:
          type: string

    PayloadB:
      type: object
      properties:
        b:
          type: string

    PayloadC:
      type: object
      properties:
        c:
          type: string
