// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ProcessPaymentBody = Payload

type Payload struct {
	Payload_OneOf *Payload_OneOf `json:"-"`
}

func (p Payload) Validate() error {
	var errors runtime.ValidationErrors
	if p.Payload_OneOf != nil {
		if v, ok := any(p.Payload_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Payload_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (p Payload) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.Payload_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Payload_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *Payload) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.Payload_OneOf == nil {
		p.Payload_OneOf = &Payload_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.Payload_OneOf); err != nil {
		return fmt.Errorf("Payload_OneOf unmarshal: %w", err)
	}

	return nil
}

type PayloadA struct {
	A *string `json:"a,omitempty"`
}

type PayloadB struct {
	B *string `json:"b,omitempty"`
}

type PayloadC struct {
	C *string `json:"c,omitempty"`
}

type Payload_OneOf struct {
	union json.RawMessage
}

func (p *Payload_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the Payload_OneOf as bytes
func (p *Payload_OneOf) Raw() json.RawMessage {
	return p.union
}

// AsPayloadA returns the union data inside the Payload_OneOf as a PayloadA
func (p *Payload_OneOf) AsPayloadA() (PayloadA, error) {
	return runtime.UnmarshalAs[PayloadA](p.union)
}

// AsValidatedPayloadA returns the union data inside the Payload_OneOf as a validated PayloadA
func (p *Payload_OneOf) AsValidatedPayloadA() (PayloadA, error) {
	val, err := p.AsPayloadA()
	if err != nil {
		var zero PayloadA
		return zero, err
	}
	if err := p.validatePayloadA(val); err != nil {
		var zero PayloadA
		return zero, err
	}
	return val, nil
}

// FromPayloadA overwrites any union data inside the Payload_OneOf as the provided PayloadA
func (p *Payload_OneOf) FromPayloadA(val PayloadA) error {
	// Validate before storing
	if err := p.validatePayloadA(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsPayloadB returns the union data inside the Payload_OneOf as a PayloadB
func (p *Payload_OneOf) AsPayloadB() (PayloadB, error) {
	return runtime.UnmarshalAs[PayloadB](p.union)
}

// AsValidatedPayloadB returns the union data inside the Payload_OneOf as a validated PayloadB
func (p *Payload_OneOf) AsValidatedPayloadB() (PayloadB, error) {
	val, err := p.AsPayloadB()
	if err != nil {
		var zero PayloadB
		return zero, err
	}
	if err := p.validatePayloadB(val); err != nil {
		var zero PayloadB
		return zero, err
	}
	return val, nil
}

// FromPayloadB overwrites any union data inside the Payload_OneOf as the provided PayloadB
func (p *Payload_OneOf) FromPayloadB(val PayloadB) error {
	// Validate before storing
	if err := p.validatePayloadB(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsPayloadC returns the union data inside the Payload_OneOf as a PayloadC
func (p *Payload_OneOf) AsPayloadC() (PayloadC, error) {
	return runtime.UnmarshalAs[PayloadC](p.union)
}

// AsValidatedPayloadC returns the union data inside the Payload_OneOf as a validated PayloadC
func (p *Payload_OneOf) AsValidatedPayloadC() (PayloadC, error) {
	val, err := p.AsPayloadC()
	if err != nil {
		var zero PayloadC
		return zero, err
	}
	if err := p.validatePayloadC(val); err != nil {
		var zero PayloadC
		return zero, err
	}
	return val, nil
}

// FromPayloadC overwrites any union data inside the Payload_OneOf as the provided PayloadC
func (p *Payload_OneOf) FromPayloadC(val PayloadC) error {
	// Validate before storing
	if err := p.validatePayloadC(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// validatePayloadA validates a PayloadA value
func (p *Payload_OneOf) validatePayloadA(val PayloadA) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePayloadB validates a PayloadB value
func (p *Payload_OneOf) validatePayloadB(val PayloadB) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePayloadC validates a PayloadC value
func (p *Payload_OneOf) validatePayloadC(val PayloadC) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (p Payload_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *Payload_OneOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
