openapi: "3.0.0"
info:
  version: 1.0.0
  title: MCP Example API
  description: API demonstrating MCP server code generation with x-mcp extension
paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      responses:
        200:
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"

  /users:
    get:
      operationId: listUsers
      summary: List all users
      x-mcp:
        name: list_users
        description: Retrieve a list of all users in the system
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      operationId: createUser
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getUser
      summary: Get a user by ID
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: deleteUser
      summary: Delete a user
      x-mcp:
        skip: true  # Don't expose delete to AI tools
      responses:
        204:
          description: User deleted

  /internal/metrics:
    get:
      operationId: getMetrics
      summary: Internal metrics endpoint
      x-mcp:
        skip: true  # Internal endpoint, not for AI
      responses:
        200:
          description: Metrics data
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    HealthStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: "ok"

    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string

    CreateUserRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

