// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type RenderingOptionsAnyOf0AmountTaxDisplay string

const (
	RenderingOptionsAnyOf0AmountTaxDisplayEmpty               RenderingOptionsAnyOf0AmountTaxDisplay = ""
	RenderingOptionsAnyOf0AmountTaxDisplayExcludeTax          RenderingOptionsAnyOf0AmountTaxDisplay = "exclude_tax"
	RenderingOptionsAnyOf0AmountTaxDisplayIncludeInclusiveTax RenderingOptionsAnyOf0AmountTaxDisplay = "include_inclusive_tax"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Rendering struct {
	Options *Rendering_Options `json:"options,omitempty"`
}

func (r Rendering) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type Rendering_Options struct {
	Rendering_Options_AnyOf *Rendering_Options_AnyOf `json:"-"`
}

func (r Rendering_Options) Validate() error {
	return schemaTypesValidate.Struct(r)
}

func (r Rendering_Options) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(r.Rendering_Options_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Rendering_Options_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (r *Rendering_Options) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if r.Rendering_Options_AnyOf == nil {
		r.Rendering_Options_AnyOf = &Rendering_Options_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, r.Rendering_Options_AnyOf); err != nil {
		return fmt.Errorf("Rendering_Options_AnyOf unmarshal: %w", err)
	}

	return nil
}

type Rendering_Options_AnyOf_0 struct {
	AmountTaxDisplay *RenderingOptionsAnyOf0AmountTaxDisplay `json:"amount_tax_display,omitempty"`
	Template         *string                                 `json:"template,omitempty" validate:"omitempty,max=5000"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Rendering_Options_AnyOf struct {
	runtime.Either[Rendering_Options_AnyOf_0, string]
}
