// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type RenderingOptionsAnyOf0AmountTaxDisplay string

const (
	Empty               RenderingOptionsAnyOf0AmountTaxDisplay = ""
	ExcludeTax          RenderingOptionsAnyOf0AmountTaxDisplay = "exclude_tax"
	IncludeInclusiveTax RenderingOptionsAnyOf0AmountTaxDisplay = "include_inclusive_tax"
)

// Validate checks if the RenderingOptionsAnyOf0AmountTaxDisplay value is valid
func (r RenderingOptionsAnyOf0AmountTaxDisplay) Validate() error {
	switch r {
	case Empty, ExcludeTax, IncludeInclusiveTax:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid RenderingOptionsAnyOf0AmountTaxDisplay value, got: %v", r))
	}
}

type GetFooResponse = map[string]any

type Rendering struct {
	Options *Rendering_Options `json:"options,omitempty"`
}

func (r Rendering) Validate() error {
	var errors runtime.ValidationErrors
	if r.Options != nil {
		if v, ok := any(r.Options).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Options", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Rendering_Options struct {
	Rendering_Options_AnyOf *Rendering_Options_AnyOf `json:"-"`
}

func (r Rendering_Options) Validate() error {
	var errors runtime.ValidationErrors
	if r.Rendering_Options_AnyOf != nil {
		if v, ok := any(r.Rendering_Options_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Rendering_Options_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (r Rendering_Options) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(r.Rendering_Options_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Rendering_Options_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (r *Rendering_Options) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if r.Rendering_Options_AnyOf == nil {
		r.Rendering_Options_AnyOf = &Rendering_Options_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, r.Rendering_Options_AnyOf); err != nil {
		return fmt.Errorf("Rendering_Options_AnyOf unmarshal: %w", err)
	}

	return nil
}

type Rendering_Options_AnyOf_0 struct {
	AmountTaxDisplay *RenderingOptionsAnyOf0AmountTaxDisplay `json:"amount_tax_display,omitempty"`
	Template         *string                                 `json:"template,omitempty" validate:"omitempty,max=5000"`
}

func (r Rendering_Options_AnyOf_0) Validate() error {
	var errors runtime.ValidationErrors
	if r.AmountTaxDisplay != nil {
		if v, ok := any(r.AmountTaxDisplay).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("AmountTaxDisplay", err)
			}
		}
	}
	if r.Template != nil {
		if err := typesValidator.Var(r.Template, "omitempty,max=5000"); err != nil {
			errors = errors.Append("Template", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Rendering_Options_AnyOf struct {
	runtime.Either[Rendering_Options_AnyOf_0, string]
}

func (r *Rendering_Options_AnyOf) Validate() error {
	if r.IsA() {
		if v, ok := any(r.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if r.IsB() {
		if v, ok := any(r.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
