openapi: 3.0.0
info:
  title: API
  description: An example of `oneOf` in responses
  version: 1.0.0

paths:
  /service/gateway:
    post:
      summary: Process payment operations
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Successful operation
          content:
            application/x-www-form-urlencoded:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ResponseA'
                  - $ref: '#/components/schemas/ResponseB'
                  - $ref: '#/components/schemas/ResponseC'

components:
  schemas:
    ResponseA:
      type: object
      properties:
        a:
          type: string

    ResponseB:
      type: object
      properties:
        b:
          type: string

    ResponseC:
      type: object
      properties:
        c:
          type: string
