// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody = map[string]any

type ProcessPaymentResponse struct {
	ProcessPayment_Response_OneOf *ProcessPayment_Response_OneOf `json:"-"`
}

func (p ProcessPaymentResponse) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPayment_Response_OneOf)
		if err != nil {
			return nil, fmt.Errorf("ProcessPayment_Response_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentResponse) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPayment_Response_OneOf == nil {
		p.ProcessPayment_Response_OneOf = &ProcessPayment_Response_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPayment_Response_OneOf); err != nil {
		return fmt.Errorf("ProcessPayment_Response_OneOf unmarshal: %w", err)
	}

	return nil
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ResponseA struct {
	A *string `json:"a,omitempty"`
}

func (r ResponseA) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseB struct {
	B *string `json:"b,omitempty"`
}

func (r ResponseB) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseC struct {
	C *string `json:"c,omitempty"`
}

func (r ResponseC) Validate() error {
	return schemaTypesValidate.Struct(r)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPayment_Response_OneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the ProcessPayment_Response_OneOf as bytes
func (p *ProcessPayment_Response_OneOf) Raw() json.RawMessage {
	return p.union
}

// AsResponseA returns the union data inside the ProcessPayment_Response_OneOf as a ResponseA
func (p *ProcessPayment_Response_OneOf) AsResponseA() (ResponseA, error) {
	return UnmarshalAs[ResponseA](p.union)
}

// FromResponseA overwrites any union data inside the ProcessPayment_Response_OneOf as the provided ResponseA
func (p *ProcessPayment_Response_OneOf) FromResponseA(v ResponseA) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseB returns the union data inside the ProcessPayment_Response_OneOf as a ResponseB
func (p *ProcessPayment_Response_OneOf) AsResponseB() (ResponseB, error) {
	return UnmarshalAs[ResponseB](p.union)
}

// FromResponseB overwrites any union data inside the ProcessPayment_Response_OneOf as the provided ResponseB
func (p *ProcessPayment_Response_OneOf) FromResponseB(v ResponseB) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseC returns the union data inside the ProcessPayment_Response_OneOf as a ResponseC
func (p *ProcessPayment_Response_OneOf) AsResponseC() (ResponseC, error) {
	return UnmarshalAs[ResponseC](p.union)
}

// FromResponseC overwrites any union data inside the ProcessPayment_Response_OneOf as the provided ResponseC
func (p *ProcessPayment_Response_OneOf) FromResponseC(v ResponseC) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

func (p ProcessPayment_Response_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProcessPayment_Response_OneOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}
