// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetNodesIDPath struct {
	// ID The ID of the node
	ID int `json:"id" validate:"required"`
}

func (g GetNodesIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetNodesIDResponse = Node

type Node struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Children []Node  `json:"children,omitempty"`
}

func (n Node) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range n.Children {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Children[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
