// Code generated by oapi-codegen. DO NOT EDIT.

package anyofwithextra

import (
	"encoding/json"
	"fmt"
)

type Client struct {
	Name string `json:"name" validate:"required"`
}

type ClientID struct {
	ID *string `json:"id,omitempty"`
}

type Address struct {
	Street               *string        `json:"street,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Getter for additional properties for <no value>. Returns the specified
// element and whether it was found
func (a Address) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for <no value>
func (a *Address) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for <no value> to handle AdditionalProperties
func (a *Address) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}

	if raw, found := object["street"]; found {
		if err := json.Unmarshal(raw, &a.Street); err != nil {
			return fmt.Errorf("error reading 'street': %w", err)
		}
		delete(object, "street")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for <no value> to handle AdditionalProperties
func (a Address) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Street != nil {
		object["street"], err = json.Marshal(a.Street)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'street': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
