// Code generated by oapi-codegen. DO NOT EDIT.

package anyofwithextra

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
)

func unmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ClientWithIDAndWithAddress struct {
	AdditionalProperties map[string]struct {
		Address *string `json:"address,omitempty"`
	} `json:"-"`
	union json.RawMessage
}

// Getter for additional properties for <no value>. Returns the specified
// element and whether it was found
func (c ClientWithIDAndWithAddress) Get(fieldName string) (value struct {
	Address *string `json:"address,omitempty"`
}, found bool) {
	if c.AdditionalProperties != nil {
		value, found = c.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for <no value>
func (c *ClientWithIDAndWithAddress) Set(fieldName string, value struct {
	Address *string `json:"address,omitempty"`
}) {
	if c.AdditionalProperties == nil {
		c.AdditionalProperties = make(map[string]struct {
			Address *string `json:"address,omitempty"`
		})
	}
	c.AdditionalProperties[fieldName] = value
}

// AsClient returns the union data inside the ClientWithIDAndWithAddress as a Client
func (c *ClientWithIDAndWithAddress) AsClient() (Client, error) {
	return unmarshalAs[Client](c.union)
}

// FromClient overwrites any union data inside the ClientWithIDAndWithAddress as the provided Client
func (c *ClientWithIDAndWithAddress) FromClient(v Client) error {
	b, err := json.Marshal(v)
	c.union = b
	return err
}

// AsClientID returns the union data inside the ClientWithIDAndWithAddress as a ClientID
func (c *ClientWithIDAndWithAddress) AsClientID() (ClientID, error) {
	return unmarshalAs[ClientID](c.union)
}

// FromClientID overwrites any union data inside the ClientWithIDAndWithAddress as the provided ClientID
func (c *ClientWithIDAndWithAddress) FromClientID(v ClientID) error {
	b, err := json.Marshal(v)
	c.union = b
	return err
}

// AsString returns the union data inside the ClientWithIDAndWithAddress as a string
func (c *ClientWithIDAndWithAddress) AsString() (string, error) {
	return unmarshalAs[string](c.union)
}

// FromString overwrites any union data inside the ClientWithIDAndWithAddress as the provided string
func (c *ClientWithIDAndWithAddress) FromString(v string) error {
	b, err := json.Marshal(v)
	c.union = b
	return err
}

// Override default JSON handling for ClientWithIDAndWithAddress to handle AdditionalProperties and union
func (c *ClientWithIDAndWithAddress) UnmarshalJSON(b []byte) error {
	if err := c.union.UnmarshalJSON(b); err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}

	if len(object) != 0 {
		c.AdditionalProperties = make(map[string]struct {
			Address *string `json:"address,omitempty"`
		})
		for fieldName, fieldBuf := range object {
			var fieldVal struct {
				Address *string `json:"address,omitempty"`
			}
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			c.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClientWithIDAndWithAddress to handle AdditionalProperties and union
func (c ClientWithIDAndWithAddress) MarshalJSON() ([]byte, error) {
	var err error
	union := c.union
	if union == nil {
		return nil, nil
	}
	b, err := union.MarshalJSON()

	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &object); err != nil {
		return nil, err
	}

	for fieldName, field := range c.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

type ClientWithID struct {
	AdditionalProperties map[string]struct {
		Address *string `json:"address,omitempty"`
	} `json:"-"`
	runtime.Either[Client, ClientID]
}

// Getter for additional properties for <no value>. Returns the specified
// element and whether it was found
func (c ClientWithID) Get(fieldName string) (value struct {
	Address *string `json:"address,omitempty"`
}, found bool) {
	if c.AdditionalProperties != nil {
		value, found = c.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for <no value>
func (c *ClientWithID) Set(fieldName string, value struct {
	Address *string `json:"address,omitempty"`
}) {
	if c.AdditionalProperties == nil {
		c.AdditionalProperties = make(map[string]struct {
			Address *string `json:"address,omitempty"`
		})
	}
	c.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClientWithID to handle AdditionalProperties and union
func (c *ClientWithID) UnmarshalJSON(b []byte) error {
	if err := c.Unmarshal(b); err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &object); err != nil {
		return err
	}

	if len(object) != 0 {
		c.AdditionalProperties = make(map[string]struct {
			Address *string `json:"address,omitempty"`
		})
		for fieldName, fieldBuf := range object {
			var fieldVal struct {
				Address *string `json:"address,omitempty"`
			}
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			c.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClientWithID to handle AdditionalProperties and union
func (c ClientWithID) MarshalJSON() ([]byte, error) {
	var err error
	union := c.Value()
	if union == nil {
		return nil, nil
	}
	b, err := json.Marshal(union)

	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &object); err != nil {
		return nil, err
	}

	for fieldName, field := range c.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
