openapi: "3.0.0"
info:
  version: 1.0.0
  title: Using complex schemas
  description: An example of `anyOf`, `allOf` and `oneOf` used together
paths:
  /foo:
    get:
      responses:
        '200':
          description: Foo
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    Order:
      type: object
      properties:
        client:
          allOf:
            - $ref: '#/components/schemas/Client'
            - properties:
                id:
                  type: integer
              required:
                - id
          anyOf:
            - $ref: '#/components/schemas/Identity'
            - $ref: '#/components/schemas/Verification'

          oneOf:
            - $ref: '#/components/schemas/Address'
            - $ref: '#/components/schemas/Location'

    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Identity:
      type: object
      required:
        - issuer
      properties:
        issuer:
          type: string

    Verification:
      type: object
      properties:
        verifier:
          type: string

    Address:
      type: object
      properties:
        city:
          type: string
        country:
          type: string


    Location:
      type: object
      properties:
        description:
          type: string
