// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Client *Order_Client `json:"client,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type Order_Client struct {
	Name               string              `json:"name" validate:"required"`
	ID                 int                 `json:"id" validate:"required"`
	Order_Client_AnyOf *Order_Client_AnyOf `json:"-"`
	Order_Client_OneOf *Order_Client_OneOf `json:"-"`
}

func (o Order_Client) Validate() error {
	return schemaTypesValidate.Struct(o)
}

func (o Order_Client) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	type _Alias_Order_Client Order_Client
	baseJSON, err := json.Marshal((_Alias_Order_Client)(o))
	if err != nil {
		return nil, err
	}
	parts = append(parts, baseJSON)

	{
		b, err := runtime.MarshalJSON(o.Order_Client_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Client_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(o.Order_Client_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Client_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Client) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_Order_Client Order_Client
		var tmp _Alias_Order_Client
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*o = Order_Client(tmp)
	}

	if o.Order_Client_AnyOf == nil {
		o.Order_Client_AnyOf = &Order_Client_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Client_AnyOf); err != nil {
		return fmt.Errorf("Order_Client_AnyOf unmarshal: %w", err)
	}

	if o.Order_Client_OneOf == nil {
		o.Order_Client_OneOf = &Order_Client_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Client_OneOf); err != nil {
		return fmt.Errorf("Order_Client_OneOf unmarshal: %w", err)
	}

	return nil
}

type Client struct {
	Name string `json:"name" validate:"required"`
}

func (c Client) Validate() error {
	return schemaTypesValidate.Struct(c)
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type Verification struct {
	Verifier *string `json:"verifier,omitempty"`
}

func (v Verification) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

func (a Address) Validate() error {
	return schemaTypesValidate.Struct(a)
}

type Location struct {
	Description *string `json:"description,omitempty"`
}

func (l Location) Validate() error {
	return schemaTypesValidate.Struct(l)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Order_Client_AnyOf struct {
	runtime.Either[Identity, Verification]
}

type Order_Client_OneOf struct {
	runtime.Either[Address, Location]
}
