// Code generated by oapi-codegen. DO NOT EDIT.

package xdeprecatedreason

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

func (c Client) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ClientWithExtension struct {
	// Deprecated: Don't use because reasons
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

func (c ClientWithExtension) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
