openapi: 3.0.0
info:
  title: Primitives
  description: An example of primitive types
  version: 1.0.0

paths:

components:
  schemas:
    response:
      type: object
      required:
        - msn-req-with-constraints
        - msn-req-without-constraints
        - msn-bool
        - msn-float
        - user-required
      properties:
        msn1:
          $ref: '#/components/schemas/msn-with-constraints'
        msn2:
          $ref: '#/components/schemas/msn-without-constraints'
        msn-req-with-constraints:
          $ref: '#/components/schemas/msn-with-constraints'
        msn-req-without-constraints:
          $ref: '#/components/schemas/msn-without-constraints'
        msn3:
          type: integer
          minimum: 1
          maximum: 100
        msn-float:
          $ref: '#/components/schemas/msn-float'
        msn-bool:
          $ref: '#/components/schemas/msn-bool'
        msn-bool-optional:
          $ref: '#/components/schemas/msn-bool'
        user-required:
          $ref: '#/components/schemas/user'
        user-optional:
          $ref: '#/components/schemas/user'
        predefined:
          type: string
          enum:
            - A
            - B
            - C

    predefined-value:
      type: object
      properties:
        value:
          $ref: '#/components/schemas/predefined'
        type:
          type: string

    predefined:
      type: string
      enum:
        - A2
        - B2
        - C2

    msn-with-constraints:
      type: string
      minLength: 4
      maxLength: 7

    msn-without-constraints:
      type: string

    msn-float:
      type: number

    msn-bool:
      type: boolean

    user:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
