// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody struct {
	A *string                `json:"a,omitempty"`
	B *string                `json:"b,omitempty"`
	C *ProcessPaymentBody_C  `json:"c,omitempty"`
	D *ProcessPaymentBody_D1 `json:"d,omitempty"`
}

func (p ProcessPaymentBody) Validate() error {
	return bodyTypesValidate.Struct(p)
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody_C struct {
	ProcessPaymentBody_C_OneOf *ProcessPaymentBody_C_OneOf `json:"-"`
}

func (p ProcessPaymentBody_C) Validate() error {
	return schemaTypesValidate.Struct(p)
}

func (p ProcessPaymentBody_C) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_C_OneOf)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_C_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody_C) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_C_OneOf == nil {
		p.ProcessPaymentBody_C_OneOf = &ProcessPaymentBody_C_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_C_OneOf); err != nil {
		return fmt.Errorf("ProcessPaymentBody_C_OneOf unmarshal: %w", err)
	}

	return nil
}

type ProcessPaymentBody_D1 struct {
	ProcessPaymentBody_D_AllOf0 *ProcessPaymentBody_D_AllOf0 `json:"-"`
}

func (p ProcessPaymentBody_D1) Validate() error {
	return schemaTypesValidate.Struct(p)
}

func (p ProcessPaymentBody_D1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_D_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_D_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody_D1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_D_AllOf0 == nil {
		p.ProcessPaymentBody_D_AllOf0 = &ProcessPaymentBody_D_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_D_AllOf0); err != nil {
		return fmt.Errorf("ProcessPaymentBody_D_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type ProcessPaymentBody_D struct {
	ProcessPaymentBody_D_AllOf0 *ProcessPaymentBody_D_AllOf0 `json:"-"`
}

func (p ProcessPaymentBody_D) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_D_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_D_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody_D) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_D_AllOf0 == nil {
		p.ProcessPaymentBody_D_AllOf0 = &ProcessPaymentBody_D_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_D_AllOf0); err != nil {
		return fmt.Errorf("ProcessPaymentBody_D_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type ProcessPaymentBody_D_AllOf0 struct {
	ProcessPaymentBody_D_AllOf0_OneOf *ProcessPaymentBody_D_AllOf0_OneOf `json:"-"`
}

func (p ProcessPaymentBody_D_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_D_AllOf0_OneOf)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_D_AllOf0_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody_D_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_D_AllOf0_OneOf == nil {
		p.ProcessPaymentBody_D_AllOf0_OneOf = &ProcessPaymentBody_D_AllOf0_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_D_AllOf0_OneOf); err != nil {
		return fmt.Errorf("ProcessPaymentBody_D_AllOf0_OneOf unmarshal: %w", err)
	}

	return nil
}

type ProcessPaymentBody_D_AllOf0_OneOf_0 struct {
	ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf `json:"-"`
}

func (p ProcessPaymentBody_D_AllOf0_OneOf_0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody_D_AllOf0_OneOf_0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf == nil {
		p.ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf = &ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf); err != nil {
		return fmt.Errorf("ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf unmarshal: %w", err)
	}

	return nil
}

type ProcessPaymentBody_D_AllOf0_OneOf_1 = map[string]any

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPaymentBody_C_OneOf struct {
	runtime.Either[string, bool]
}

type ProcessPaymentBody_D_AllOf0_OneOf struct {
	runtime.Either[ProcessPaymentBody_D_AllOf0_OneOf_0, ProcessPaymentBody_D_AllOf0_OneOf_1]
}

type ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as bytes
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) Raw() json.RawMessage {
	return p.union
}

// AsBool returns the union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as a bool
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) AsBool() (bool, error) {
	return UnmarshalAs[bool](p.union)
}

// FromBool overwrites any union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as the provided bool
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) FromBool(v bool) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsFloat32 returns the union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as a float32
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) AsFloat32() (float32, error) {
	return UnmarshalAs[float32](p.union)
}

// FromFloat32 overwrites any union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as the provided float32
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) FromFloat32(v float32) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsString returns the union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as a string
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) AsString() (string, error) {
	return UnmarshalAs[string](p.union)
}

// FromString overwrites any union data inside the ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf as the provided string
func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) FromString(v string) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

func (p ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProcessPaymentBody_D_AllOf0_OneOf_0_AnyOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}
