// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type StatusCode int

const (
	StatusCodeN200 StatusCode = 200
	StatusCodeN404 StatusCode = 404
	StatusCodeN500 StatusCode = 500
)

// Validate checks if the StatusCode value is valid
func (s StatusCode) Validate() error {
	switch s {
	case StatusCodeN200, StatusCodeN404, StatusCodeN500:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid StatusCode value, got: %v", s))
	}
}

type Priority float32

const (
	PriorityN10 Priority = 1.0
	PriorityN25 Priority = 2.5
	PriorityN50 Priority = 5.0
)

// Validate checks if the Priority value is valid
func (p Priority) Validate() error {
	switch p {
	case PriorityN10, PriorityN25, PriorityN50:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid Priority value, got: %v", p))
	}
}

type Color string

const (
	ColorBlue  Color = "blue"
	ColorGreen Color = "green"
	ColorRed   Color = "red"
)

// Validate checks if the Color value is valid
func (c Color) Validate() error {
	switch c {
	case ColorBlue, ColorGreen, ColorRed:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid Color value, got: %v", c))
	}
}

type TestObject struct {
	Status   *StatusCode `json:"status,omitempty"`
	Priority *Priority   `json:"priority,omitempty"`
	Color    Color       `json:"color" validate:"required"`
}

func (t TestObject) Validate() error {
	var errors runtime.ValidationErrors
	if t.Status != nil {
		if v, ok := any(t.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if t.Priority != nil {
		if v, ok := any(t.Priority).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Priority", err)
			}
		}
	}
	if v, ok := any(t.Color).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Color", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type TestObjectRequired struct {
	Status   StatusCode `json:"status" validate:"required"`
	Priority Priority   `json:"priority" validate:"required"`
	Color    Color      `json:"color" validate:"required"`
}

func (t TestObjectRequired) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(t.Status).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Status", err)
		}
	}
	if v, ok := any(t.Priority).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Priority", err)
		}
	}
	if v, ok := any(t.Color).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Color", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
