// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type FileType string

const (
	FileTypeFile FileType = "file"
)

// Validate checks if the FileType value is valid
func (f FileType) Validate() error {
	switch f {
	case FileTypeFile:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FileType value, got: %v", f))
	}
}

type FolderType string

const (
	FolderTypeFolder FolderType = "folder"
)

// Validate checks if the FolderType value is valid
func (f FolderType) Validate() error {
	switch f {
	case FolderTypeFolder:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FolderType value, got: %v", f))
	}
}

type WebLinkType string

const (
	WebLinkTypeWebLink WebLinkType = "web_link"
)

// Validate checks if the WebLinkType value is valid
func (w WebLinkType) Validate() error {
	switch w {
	case WebLinkTypeWebLink:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid WebLinkType value, got: %v", w))
	}
}

type CollaborationRole string

const (
	CollaborationRoleEditor CollaborationRole = "editor"
	CollaborationRoleOwner  CollaborationRole = "owner"
	CollaborationRoleViewer CollaborationRole = "viewer"
)

// Validate checks if the CollaborationRole value is valid
func (c CollaborationRole) Validate() error {
	switch c {
	case CollaborationRoleEditor, CollaborationRoleOwner, CollaborationRoleViewer:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid CollaborationRole value, got: %v", c))
	}
}

type GetCollaborationResponseRole string

const (
	GetCollaborationResponseRoleEditor GetCollaborationResponseRole = "editor"
	GetCollaborationResponseRoleOwner  GetCollaborationResponseRole = "owner"
	GetCollaborationResponseRoleViewer GetCollaborationResponseRole = "viewer"
)

// Validate checks if the GetCollaborationResponseRole value is valid
func (g GetCollaborationResponseRole) Validate() error {
	switch g {
	case GetCollaborationResponseRoleEditor, GetCollaborationResponseRoleOwner, GetCollaborationResponseRoleViewer:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid GetCollaborationResponseRole value, got: %v", g))
	}
}

type GetCollaborationResponse struct {
	ID   string                           `json:"id" validate:"required"`
	Item *GetCollaboration_Response_Item1 `json:"item,omitempty"`
	Role *GetCollaborationResponseRole    `json:"role,omitempty"`
}

type File struct {
	Type FileType `json:"type" validate:"required"`
	ID   string   `json:"id" validate:"required"`
	Name *string  `json:"name,omitempty"`
}

func (f File) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(f.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(f.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Folder struct {
	Type FolderType `json:"type" validate:"required"`
	ID   string     `json:"id" validate:"required"`
	Name *string    `json:"name,omitempty"`
}

func (f Folder) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(f.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(f.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type WebLink struct {
	Type WebLinkType `json:"type" validate:"required"`
	ID   string      `json:"id" validate:"required"`
	URL  *string     `json:"url,omitempty"`
}

func (w WebLink) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(w.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(w.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Collaboration struct {
	ID   string               `json:"id" validate:"required"`
	Item *Collaboration_Item1 `json:"item,omitempty"`
	Role *CollaborationRole   `json:"role,omitempty"`
}

func (c Collaboration) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if c.Item != nil {
		if v, ok := any(c.Item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Item", err)
			}
		}
	}
	if c.Role != nil {
		if v, ok := any(c.Role).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Role", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Collaboration_Item1 struct {
	Collaboration_Item_AllOf0 *Collaboration_Item_AllOf0 `json:"-"`
}

func (c Collaboration_Item1) Validate() error {
	var errors runtime.ValidationErrors
	if c.Collaboration_Item_AllOf0 != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Collaboration_Item_AllOf0", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c Collaboration_Item1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0 == nil {
		c.Collaboration_Item_AllOf0 = &Collaboration_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item1 struct {
	GetCollaboration_Response_Item_AllOf0 *GetCollaboration_Response_Item_AllOf0 `json:"-"`
}

func (g GetCollaboration_Response_Item1) Validate() error {
	var errors runtime.ValidationErrors
	if g.GetCollaboration_Response_Item_AllOf0 != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("GetCollaboration_Response_Item_AllOf0", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (g GetCollaboration_Response_Item1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0 == nil {
		g.GetCollaboration_Response_Item_AllOf0 = &GetCollaboration_Response_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type Collaboration_Item struct {
	Collaboration_Item_AllOf0 *Collaboration_Item_AllOf0 `json:"-"`
}

func (c Collaboration_Item) Validate() error {
	var errors runtime.ValidationErrors
	if c.Collaboration_Item_AllOf0 != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Collaboration_Item_AllOf0", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c Collaboration_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0 == nil {
		c.Collaboration_Item_AllOf0 = &Collaboration_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type Collaboration_Item_AllOf0 struct {
	Collaboration_Item_AllOf0_OneOf *Collaboration_Item_AllOf0_OneOf `json:"-"`
}

func (c Collaboration_Item_AllOf0) Validate() error {
	var errors runtime.ValidationErrors
	if c.Collaboration_Item_AllOf0_OneOf != nil {
		if v, ok := any(c.Collaboration_Item_AllOf0_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Collaboration_Item_AllOf0_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c Collaboration_Item_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.Collaboration_Item_AllOf0_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Collaboration_Item_AllOf0_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *Collaboration_Item_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.Collaboration_Item_AllOf0_OneOf == nil {
		c.Collaboration_Item_AllOf0_OneOf = &Collaboration_Item_AllOf0_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.Collaboration_Item_AllOf0_OneOf); err != nil {
		return fmt.Errorf("Collaboration_Item_AllOf0_OneOf unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item struct {
	GetCollaboration_Response_Item_AllOf0 *GetCollaboration_Response_Item_AllOf0 `json:"-"`
}

func (g GetCollaboration_Response_Item) Validate() error {
	var errors runtime.ValidationErrors
	if g.GetCollaboration_Response_Item_AllOf0 != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("GetCollaboration_Response_Item_AllOf0", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (g GetCollaboration_Response_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0 == nil {
		g.GetCollaboration_Response_Item_AllOf0 = &GetCollaboration_Response_Item_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0 unmarshal: %w", err)
	}

	return nil
}

type GetCollaboration_Response_Item_AllOf0 struct {
	GetCollaboration_Response_Item_AllOf0_OneOf *GetCollaboration_Response_Item_AllOf0_OneOf `json:"-"`
}

func (g GetCollaboration_Response_Item_AllOf0) Validate() error {
	var errors runtime.ValidationErrors
	if g.GetCollaboration_Response_Item_AllOf0_OneOf != nil {
		if v, ok := any(g.GetCollaboration_Response_Item_AllOf0_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("GetCollaboration_Response_Item_AllOf0_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (g GetCollaboration_Response_Item_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetCollaboration_Response_Item_AllOf0_OneOf)
		if err != nil {
			return nil, fmt.Errorf("GetCollaboration_Response_Item_AllOf0_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetCollaboration_Response_Item_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetCollaboration_Response_Item_AllOf0_OneOf == nil {
		g.GetCollaboration_Response_Item_AllOf0_OneOf = &GetCollaboration_Response_Item_AllOf0_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetCollaboration_Response_Item_AllOf0_OneOf); err != nil {
		return fmt.Errorf("GetCollaboration_Response_Item_AllOf0_OneOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Collaboration_Item_AllOf0_OneOf struct {
	union json.RawMessage
}

func (c *Collaboration_Item_AllOf0_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the Collaboration_Item_AllOf0_OneOf as bytes
func (c *Collaboration_Item_AllOf0_OneOf) Raw() json.RawMessage {
	return c.union
}

// AsFile returns the union data inside the Collaboration_Item_AllOf0_OneOf as a File
func (c *Collaboration_Item_AllOf0_OneOf) AsFile() (File, error) {
	return UnmarshalAs[File](c.union)
}

// AsValidatedFile returns the union data inside the Collaboration_Item_AllOf0_OneOf as a validated File
func (c *Collaboration_Item_AllOf0_OneOf) AsValidatedFile() (File, error) {
	val, err := c.AsFile()
	if err != nil {
		var zero File
		return zero, err
	}
	if err := c.validateFile(val); err != nil {
		var zero File
		return zero, err
	}
	return val, nil
}

// FromFile overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided File
func (c *Collaboration_Item_AllOf0_OneOf) FromFile(val File) error {
	// Validate before storing
	if err := c.validateFile(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsFolder returns the union data inside the Collaboration_Item_AllOf0_OneOf as a Folder
func (c *Collaboration_Item_AllOf0_OneOf) AsFolder() (Folder, error) {
	return UnmarshalAs[Folder](c.union)
}

// AsValidatedFolder returns the union data inside the Collaboration_Item_AllOf0_OneOf as a validated Folder
func (c *Collaboration_Item_AllOf0_OneOf) AsValidatedFolder() (Folder, error) {
	val, err := c.AsFolder()
	if err != nil {
		var zero Folder
		return zero, err
	}
	if err := c.validateFolder(val); err != nil {
		var zero Folder
		return zero, err
	}
	return val, nil
}

// FromFolder overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided Folder
func (c *Collaboration_Item_AllOf0_OneOf) FromFolder(val Folder) error {
	// Validate before storing
	if err := c.validateFolder(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsWebLink returns the union data inside the Collaboration_Item_AllOf0_OneOf as a WebLink
func (c *Collaboration_Item_AllOf0_OneOf) AsWebLink() (WebLink, error) {
	return UnmarshalAs[WebLink](c.union)
}

// AsValidatedWebLink returns the union data inside the Collaboration_Item_AllOf0_OneOf as a validated WebLink
func (c *Collaboration_Item_AllOf0_OneOf) AsValidatedWebLink() (WebLink, error) {
	val, err := c.AsWebLink()
	if err != nil {
		var zero WebLink
		return zero, err
	}
	if err := c.validateWebLink(val); err != nil {
		var zero WebLink
		return zero, err
	}
	return val, nil
}

// FromWebLink overwrites any union data inside the Collaboration_Item_AllOf0_OneOf as the provided WebLink
func (c *Collaboration_Item_AllOf0_OneOf) FromWebLink(val WebLink) error {
	// Validate before storing
	if err := c.validateWebLink(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// validateFile validates a File value
func (c *Collaboration_Item_AllOf0_OneOf) validateFile(val File) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateFolder validates a Folder value
func (c *Collaboration_Item_AllOf0_OneOf) validateFolder(val Folder) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateWebLink validates a WebLink value
func (c *Collaboration_Item_AllOf0_OneOf) validateWebLink(val WebLink) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (c Collaboration_Item_AllOf0_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := c.union.MarshalJSON()

	return bts, err
}

func (c *Collaboration_Item_AllOf0_OneOf) UnmarshalJSON(bts []byte) error {
	err := c.union.UnmarshalJSON(bts)

	return err
}

type GetCollaboration_Response_Item_AllOf0_OneOf struct {
	union json.RawMessage
}

func (g *GetCollaboration_Response_Item_AllOf0_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as bytes
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) Raw() json.RawMessage {
	return g.union
}

// AsFile returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a File
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsFile() (File, error) {
	return UnmarshalAs[File](g.union)
}

// AsValidatedFile returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a validated File
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsValidatedFile() (File, error) {
	val, err := g.AsFile()
	if err != nil {
		var zero File
		return zero, err
	}
	if err := g.validateFile(val); err != nil {
		var zero File
		return zero, err
	}
	return val, nil
}

// FromFile overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided File
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromFile(val File) error {
	// Validate before storing
	if err := g.validateFile(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsFolder returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a Folder
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsFolder() (Folder, error) {
	return UnmarshalAs[Folder](g.union)
}

// AsValidatedFolder returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a validated Folder
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsValidatedFolder() (Folder, error) {
	val, err := g.AsFolder()
	if err != nil {
		var zero Folder
		return zero, err
	}
	if err := g.validateFolder(val); err != nil {
		var zero Folder
		return zero, err
	}
	return val, nil
}

// FromFolder overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided Folder
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromFolder(val Folder) error {
	// Validate before storing
	if err := g.validateFolder(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsWebLink returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a WebLink
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsWebLink() (WebLink, error) {
	return UnmarshalAs[WebLink](g.union)
}

// AsValidatedWebLink returns the union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as a validated WebLink
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) AsValidatedWebLink() (WebLink, error) {
	val, err := g.AsWebLink()
	if err != nil {
		var zero WebLink
		return zero, err
	}
	if err := g.validateWebLink(val); err != nil {
		var zero WebLink
		return zero, err
	}
	return val, nil
}

// FromWebLink overwrites any union data inside the GetCollaboration_Response_Item_AllOf0_OneOf as the provided WebLink
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) FromWebLink(val WebLink) error {
	// Validate before storing
	if err := g.validateWebLink(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// validateFile validates a File value
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) validateFile(val File) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateFolder validates a Folder value
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) validateFolder(val Folder) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateWebLink validates a WebLink value
func (g *GetCollaboration_Response_Item_AllOf0_OneOf) validateWebLink(val WebLink) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (g GetCollaboration_Response_Item_AllOf0_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := g.union.MarshalJSON()

	return bts, err
}

func (g *GetCollaboration_Response_Item_AllOf0_OneOf) UnmarshalJSON(bts []byte) error {
	err := g.union.UnmarshalJSON(bts)

	return err
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
