// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetTestResponse struct {
	TotalClicks     *int                        `json:"totalClicks,omitempty"`
	HourlyBreakDown map[string]AggregatedResult `json:"hourlyBreakDown,omitempty"`
}

type AggregatedResult struct {
	TotalClicks     *int                        `json:"totalClicks,omitempty"`
	HourlyBreakDown map[string]AggregatedResult `json:"hourlyBreakDown,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
