openapi: "3.0.0"
info:
  version: 1.0.0
  title: Using complex schemas
  description: An example of `anyOf` with extra properties
paths:
  /foo:
    get:
      responses:
        '200':
          description: Foo
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    # base types
    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    ClientId:
      type: object
      properties:
        id:
          type: string

    ClientWithIdAndWithAddress:
      anyOf:
        - $ref: '#/components/schemas/Client'
        - $ref: '#/components/schemas/ClientId'
        - type: string
      additionalProperties:
        properties:
          address:
            type: string

    ClientWithId:
      anyOf:
        - $ref: '#/components/schemas/Client'
        - $ref: '#/components/schemas/ClientId'
      additionalProperties:
        properties:
          address:
            type: string

    Address:
      type: object
      properties:
        street:
          type: string
      additionalProperties: true
