// Code generated by oapi-codegen. DO NOT EDIT.

package example5

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetCharge(ctx context.Context, options *GetChargeRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetChargeResponse, error)
}

func (c *Client) GetCharge(ctx context.Context, options *GetChargeRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetChargeResponse, error) {
	var err error

	queryEncoding := map[string]runtime.QueryEncoding{
		"expand": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/charges/{id}",
		Method:        "GET",
		Options:       options,
		QueryEncoding: queryEncoding,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetChargeResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetChargeResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/charges/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// GetChargeRequestOptions is the options needed to make a request to GetCharge.
type GetChargeRequestOptions struct {
	PathParams *GetChargePath
	Query      *GetChargeQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetChargeRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetChargeRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetChargeRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetChargeRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetChargeRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

type GetChargePath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetChargePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetChargeQuery struct {
	Expand []string `json:"expand,omitempty"`
	Status []string `json:"status,omitempty"`
}

type GetChargeResponse = Charge

type Charge struct {
	ID       *string `json:"id,omitempty"`
	Amount   *int    `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
