// Code generated by oapi-codegen. DO NOT EDIT.

package namingconflict

type Type string

const (
	TypeACHDebit                    Type = "ach_debit"
	TypeSourceTypeACHCreditTransfer Type = "source_type_ach_credit_transfer"
)

type Source struct {
	ACHCreditTransfer *SourceTypeACHCreditTransfer `json:"ach_credit_transfer,omitempty"`
}

type SourceTypeACHCreditTransfer struct {
	AccountNumber *string `json:"account_number,omitempty"`
	BankName      *string `json:"bank_name,omitempty"`
}
