// Code generated by oapi-codegen. DO NOT EDIT.

package namingconflict

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type Type string

const (
	TypeDebit      Type = "debit"
	TypeSourceType Type = "source_type"
)

// Validate checks if the Type value is valid
func (t Type) Validate() error {
	switch t {
	case TypeDebit, TypeSourceType:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid Type value, got: %v", t))
	}
}

type Source struct {
	CreditTransfer *SourceType `json:"credit_transfer,omitempty"`
}

func (s Source) Validate() error {
	var errors runtime.ValidationErrors
	if s.CreditTransfer != nil {
		if v, ok := any(s.CreditTransfer).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CreditTransfer", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type SourceType struct {
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
