// Code generated by oapi-codegen. DO NOT EDIT.

package circularucr

import (
	"github.com/go-playground/validator/v10"
)

// OrgModelType Structure type
type OrgModelType string

const (
	OrgModelTypeDepartment   OrgModelType = "Department"
	OrgModelTypeDivision     OrgModelType = "Division"
	OrgModelTypeOrganization OrgModelType = "Organization"
)

type AcctstructureResponse struct {
	Response *OrgModel `json:"response,omitempty"`
	Success  *bool     `json:"success,omitempty"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type OrgByIDResponseWrapperModel struct {
	Response *OrgModel `json:"response,omitempty"`
	Success  *bool     `json:"success,omitempty"`
}

func (o OrgByIDResponseWrapperModel) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type OrgModel struct {
	// Type Structure type
	Type     *OrgModelType `json:"type,omitempty"`
	Parent   *OrgModel     `json:"parent,omitempty"`
	Children []OrgModel    `json:"children,omitempty"`
}

func (o OrgModel) Validate() error {
	return schemaTypesValidate.Struct(o)
}
