// Code generated by oapi-codegen. DO NOT EDIT.

package circularucr

import (
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// OrgModelType Structure type
type OrgModelType string

const (
	Department   OrgModelType = "Department"
	Division     OrgModelType = "Division"
	Organization OrgModelType = "Organization"
)

// Validate checks if the OrgModelType value is valid
func (o OrgModelType) Validate() error {
	switch o {
	case Department, Division, Organization:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OrgModelType value, got: %v", o))
	}
}

type AcctstructureResponse = OrgByIDResponseWrapperModel

type OrgByIDResponseWrapperModel struct {
	Response *OrgModel `json:"response,omitempty"`
	Success  *bool     `json:"success,omitempty"`
}

func (o OrgByIDResponseWrapperModel) Validate() error {
	var errors runtime.ValidationErrors
	if o.Response != nil {
		if v, ok := any(o.Response).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Response", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type OrgModel struct {
	// Type Structure type
	Type     *OrgModelType `json:"type,omitempty"`
	Parent   *OrgModel     `json:"parent,omitempty"`
	Children []OrgModel    `json:"children,omitempty"`
}

func (o OrgModel) Validate() error {
	var errors runtime.ValidationErrors
	if o.Type != nil {
		if v, ok := any(o.Type).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Type", err)
			}
		}
	}
	if o.Parent != nil {
		if v, ok := any(o.Parent).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Parent", err)
			}
		}
	}
	for i, item := range o.Children {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Children[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
