// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Client *OrderClientOneOf `json:"client,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type Verification struct {
	Verifier *string `json:"verifier,omitempty"`
}

func (v Verification) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

func (a Address) Validate() error {
	return schemaTypesValidate.Struct(a)
}

type Location struct {
	Description *string `json:"description,omitempty"`
}

func (l Location) Validate() error {
	return schemaTypesValidate.Struct(l)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type OrderClientAnyOf struct {
	runtime.Either[Identity, Verification]
}

func (o *OrderClientAnyOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderClientAnyOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}

type OrderClientOneOf struct {
	runtime.Either[Address, Location]
}

func (o *OrderClientOneOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderClientOneOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}
