// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

type Order struct {
	Client *Order_Client `json:"client,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if o.Client != nil {
		if v, ok := any(o.Client).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Client", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Client struct {
	Order_Client_AnyOf *Order_Client_AnyOf `json:"-"`
	Order_Client_OneOf *Order_Client_OneOf `json:"-"`
}

func (o Order_Client) Validate() error {
	var errors runtime.ValidationErrors
	if o.Order_Client_AnyOf != nil {
		if v, ok := any(o.Order_Client_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Client_AnyOf", err)
			}
		}
	}
	if o.Order_Client_OneOf != nil {
		if v, ok := any(o.Order_Client_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Client_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (o Order_Client) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Client_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Client_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(o.Order_Client_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Client_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Client) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Client_AnyOf == nil {
		o.Order_Client_AnyOf = &Order_Client_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Client_AnyOf); err != nil {
		return fmt.Errorf("Order_Client_AnyOf unmarshal: %w", err)
	}

	if o.Order_Client_OneOf == nil {
		o.Order_Client_OneOf = &Order_Client_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Client_OneOf); err != nil {
		return fmt.Errorf("Order_Client_OneOf unmarshal: %w", err)
	}

	return nil
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(i))
}

type Verification struct {
	Verifier *string `json:"verifier,omitempty"`
}

type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

type Location struct {
	Description *string `json:"description,omitempty"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Order_Client_AnyOf struct {
	runtime.Either[Identity, Verification]
}

func (o *Order_Client_AnyOf) Validate() error {
	if o.IsA() {
		if v, ok := any(o.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if o.IsB() {
		if v, ok := any(o.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Order_Client_OneOf struct {
	runtime.Either[Address, Location]
}

func (o *Order_Client_OneOf) Validate() error {
	if o.IsA() {
		if v, ok := any(o.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if o.IsB() {
		if v, ok := any(o.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
