// Code generated by oapi-codegen. DO NOT EDIT.

package slicespointer

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type Payments []string

func (p Payments) Validate() error {
	if p == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	if len(p) < 1 {
		errors = errors.Add("Array", fmt.Sprintf("must have at least 1 items, got %d", len(p)))
	}
	for i, item := range p {
		if err := typesValidator.Var(item, "omitempty,min=3"); err != nil {
			errors = errors.Append(fmt.Sprintf("[%d]", i), err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Data map[string]any

type User struct {
	Payments Payments       `json:"payments,omitempty"`
	Data     Data           `json:"data,omitempty"`
	Prefs    []string       `json:"prefs,omitempty"`
	Address  map[string]any `json:"address,omitempty"`
}

func (u User) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.Payments).(runtime.Validator); ok && v != nil {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Payments", err)
		}
	}
	if v, ok := any(u.Data).(runtime.Validator); ok && v != nil {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Data", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
