// Code generated by oapi-codegen. DO NOT EDIT.

package example3

type GetUserSingleResponse struct {
	ID      string  `json:"id" validate:"required"`
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
}

type GetUserUnion1Response struct {
	ID      string  `json:"id" validate:"required"`
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
}
