// Code generated by oapi-codegen. DO NOT EDIT.

package example3

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

type User struct {
	ID      string  `json:"id" validate:"required"`
	Name    *string `json:"name,omitempty"`
	Address *string `json:"address,omitempty"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}
