// Code generated by oapi-codegen. DO NOT EDIT.

package example3

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
)

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type GetUserUnion1_Response_OneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the GetUserUnion1_Response_OneOf as bytes
func (g *GetUserUnion1_Response_OneOf) Raw() json.RawMessage {
	return g.union
}

// AsUser returns the union data inside the GetUserUnion1_Response_OneOf as a User
func (g *GetUserUnion1_Response_OneOf) AsUser() (User, error) {
	return UnmarshalAs[User](g.union)
}

// FromUser overwrites any union data inside the GetUserUnion1_Response_OneOf as the provided User
func (g *GetUserUnion1_Response_OneOf) FromUser(v User) error {
	bts, err := json.Marshal(v)
	g.union = bts
	return err
}

func (g GetUserUnion1_Response_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := g.union.MarshalJSON()

	return bts, err
}

func (g *GetUserUnion1_Response_OneOf) UnmarshalJSON(bts []byte) error {
	err := g.union.UnmarshalJSON(bts)

	return err
}

type GetUserUnion2_Response_OneOf struct {
	runtime.Either[User, string]
}

type GetUserUnion3_Response_OneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the GetUserUnion3_Response_OneOf as bytes
func (g *GetUserUnion3_Response_OneOf) Raw() json.RawMessage {
	return g.union
}

// AsUser returns the union data inside the GetUserUnion3_Response_OneOf as a User
func (g *GetUserUnion3_Response_OneOf) AsUser() (User, error) {
	return UnmarshalAs[User](g.union)
}

// FromUser overwrites any union data inside the GetUserUnion3_Response_OneOf as the provided User
func (g *GetUserUnion3_Response_OneOf) FromUser(v User) error {
	bts, err := json.Marshal(v)
	g.union = bts
	return err
}

// AsString returns the union data inside the GetUserUnion3_Response_OneOf as a string
func (g *GetUserUnion3_Response_OneOf) AsString() (string, error) {
	return UnmarshalAs[string](g.union)
}

// FromString overwrites any union data inside the GetUserUnion3_Response_OneOf as the provided string
func (g *GetUserUnion3_Response_OneOf) FromString(v string) error {
	bts, err := json.Marshal(v)
	g.union = bts
	return err
}

// AsInt returns the union data inside the GetUserUnion3_Response_OneOf as a int
func (g *GetUserUnion3_Response_OneOf) AsInt() (int, error) {
	return UnmarshalAs[int](g.union)
}

// FromInt overwrites any union data inside the GetUserUnion3_Response_OneOf as the provided int
func (g *GetUserUnion3_Response_OneOf) FromInt(v int) error {
	bts, err := json.Marshal(v)
	g.union = bts
	return err
}

func (g GetUserUnion3_Response_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := g.union.MarshalJSON()

	return bts, err
}

func (g *GetUserUnion3_Response_OneOf) UnmarshalJSON(bts []byte) error {
	err := g.union.UnmarshalJSON(bts)

	return err
}
