openapi: 3.0.0
info:
  title: API
  description: An example of enums
  version: 1.0.0

paths:
components:
  schemas:
    Product:
      type: object
      properties:
        variations:
          type: string
          enum:
            - A
            - B
            - C
