// Code generated by oapi-codegen. DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type OrderStatus string

const (
	Confirmed OrderStatus = "confirmed"
	Delivered OrderStatus = "delivered"
	Pending   OrderStatus = "pending"
	Shipped   OrderStatus = "shipped"
)

// Validate checks if the OrderStatus value is valid
func (o OrderStatus) Validate() error {
	switch o {
	case Confirmed, Delivered, Pending, Shipped:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OrderStatus value, got: %v", o))
	}
}
