// Code generated by oapi-codegen. DO NOT EDIT.
package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares []func(http.Handler) http.Handler
	errHandler  OapiErrorHandler
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw func(http.Handler) http.Handler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// WithErrorHandler sets a custom error handler for the router.
// If not set, OapiOapiDefaultErrorHandler is used.
func WithErrorHandler(h OapiErrorHandler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.errHandler = h
	}
}

// NewRouter creates a new chi.Router with the given service implementation.
func NewRouter(svc ServiceInterface, opts ...RouterOption) chi.Router {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	adapter := NewHTTPAdapter(svc, cfg.errHandler)

	r := chi.NewRouter()
	for _, mw := range cfg.middlewares {
		r.Use(mw)
	}
	r.Method("GET", "/health", http.HandlerFunc(adapter.HealthCheck))
	r.Method("GET", "/users", http.HandlerFunc(adapter.ListUsers))
	r.Method("POST", "/users", http.HandlerFunc(adapter.CreateUser))
	r.Method("GET", "/users/{id}", http.HandlerFunc(adapter.GetUser))
	r.Method("DELETE", "/users/{id}", http.HandlerFunc(adapter.DeleteUser))

	return r
}
