// Code generated by oapi-codegen. DO NOT EDIT.

package example4

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetOrder(ctx context.Context, options *GetOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetOrderResponse, error)
}

func (c *Client) GetOrder(ctx context.Context, options *GetOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetOrderResponse, error) {
	var err error
	queryEncoding := make(map[string]runtime.QueryEncoding)
	queryEncoding["client_secret"] = runtime.QueryEncoding{
		Style: "form",
	}
	queryEncoding["expand"] = runtime.QueryEncoding{
		Style:   "deepObject",
		Explode: &[]bool{true}[0],
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/order/{id}",
		Method:        "GET",
		Options:       options,
		QueryEncoding: queryEncoding,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetOrderResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetOrderResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/order/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

// GetOrderRequestOptions is the options needed to make a request to GetOrder.
type GetOrderRequestOptions struct {
	PathParams *GetOrderPath
	Query      *GetOrderQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetOrderRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if err := clientOptionsValidate.Struct(o.PathParams); err != nil {
		errors = append(errors, runtime.NewValidationErrorsFromErrors("PathParams", []error{err})...)
	}

	if err := clientOptionsValidate.Struct(o.Query); err != nil {
		errors = append(errors, runtime.NewValidationErrorsFromErrors("Query", []error{err})...)
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetOrderRequestOptions) GetPathParams() (map[string]any, error) {
	return asMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetOrderRequestOptions) GetQuery() (map[string]any, error) {
	return asMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetOrderRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetOrderRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

var pathTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type GetOrderPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetOrderPath) Validate() error {
	return pathTypesValidate.Struct(g)
}

var queryTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type GetOrderQuery struct {
	ClientSecret *string  `json:"client_secret,omitempty"`
	Expand       []string `json:"expand,omitempty"`
}

func (g GetOrderQuery) Validate() error {
	return queryTypesValidate.Struct(g)
}

type GetOrderResponse = map[string]any
