// Code generated by oapi-codegen. DO NOT EDIT.

package nestedanyof

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type CreditCardPaymentType string

const (
	CreditCard CreditCardPaymentType = "credit_card"
)

// Validate checks if the CreditCardPaymentType value is valid
func (c CreditCardPaymentType) Validate() error {
	switch c {
	case CreditCard:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid CreditCardPaymentType value, got: %v", c))
	}
}

type BankTransferPaymentType string

const (
	BankTransfer BankTransferPaymentType = "bank_transfer"
)

// Validate checks if the BankTransferPaymentType value is valid
func (b BankTransferPaymentType) Validate() error {
	switch b {
	case BankTransfer:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid BankTransferPaymentType value, got: %v", b))
	}
}

type DomesticAccountAccountType string

const (
	Domestic DomesticAccountAccountType = "domestic"
)

// Validate checks if the DomesticAccountAccountType value is valid
func (d DomesticAccountAccountType) Validate() error {
	switch d {
	case Domestic:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid DomesticAccountAccountType value, got: %v", d))
	}
}

type InternationalAccountAccountType string

const (
	International InternationalAccountAccountType = "international"
)

// Validate checks if the InternationalAccountAccountType value is valid
func (i InternationalAccountAccountType) Validate() error {
	switch i {
	case International:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid InternationalAccountAccountType value, got: %v", i))
	}
}

type PersonalBeneficiaryBeneficiaryType string

const (
	Personal PersonalBeneficiaryBeneficiaryType = "personal"
)

// Validate checks if the PersonalBeneficiaryBeneficiaryType value is valid
func (p PersonalBeneficiaryBeneficiaryType) Validate() error {
	switch p {
	case Personal:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid PersonalBeneficiaryBeneficiaryType value, got: %v", p))
	}
}

type BusinessBeneficiaryBeneficiaryType string

const (
	Business BusinessBeneficiaryBeneficiaryType = "business"
)

// Validate checks if the BusinessBeneficiaryBeneficiaryType value is valid
func (b BusinessBeneficiaryBeneficiaryType) Validate() error {
	switch b {
	case Business:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid BusinessBeneficiaryBeneficiaryType value, got: %v", b))
	}
}

type DigitalWalletPaymentType string

const (
	DigitalWallet DigitalWalletPaymentType = "digital_wallet"
)

// Validate checks if the DigitalWalletPaymentType value is valid
func (d DigitalWalletPaymentType) Validate() error {
	switch d {
	case DigitalWallet:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid DigitalWalletPaymentType value, got: %v", d))
	}
}

type PaymentMethod struct {
	PaymentMethod_AnyOf *PaymentMethod_AnyOf `json:"-"`
}

func (p PaymentMethod) Validate() error {
	var errors runtime.ValidationErrors
	if p.PaymentMethod_AnyOf != nil {
		if v, ok := any(p.PaymentMethod_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PaymentMethod_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (p PaymentMethod) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.PaymentMethod_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("PaymentMethod_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *PaymentMethod) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.PaymentMethod_AnyOf == nil {
		p.PaymentMethod_AnyOf = &PaymentMethod_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.PaymentMethod_AnyOf); err != nil {
		return fmt.Errorf("PaymentMethod_AnyOf unmarshal: %w", err)
	}

	return nil
}

type CreditCardPayment struct {
	Type           CreditCardPaymentType `json:"type" validate:"required"`
	CardNumber     string                `json:"cardNumber" sensitive:"" validate:"required"`
	Cvv            *string               `json:"cvv,omitempty" sensitive:""`
	BillingAddress *Address              `json:"billingAddress,omitempty"`
}

func (c CreditCardPayment) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(c.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(c.CardNumber, "required"); err != nil {
		errors = errors.Append("CardNumber", err)
	}
	if c.BillingAddress != nil {
		if v, ok := any(c.BillingAddress).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BillingAddress", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c CreditCardPayment) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_CreditCardPayment CreditCardPayment
	masked := _Alias_CreditCardPayment(c)
	// Mask sensitive field: CardNumber
	{
		maskedVal := runtime.MaskSensitiveValue(masked.CardNumber, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 4,
		})
		masked.CardNumber = maskedVal.(string)
	}
	// Mask sensitive field: Cvv
	if masked.Cvv != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Cvv, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Cvv = nil
		} else {
			val := maskedVal.(string)
			masked.Cvv = &val
		}
	}

	return json.Marshal(masked)
}

func (c *CreditCardPayment) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_CreditCardPayment CreditCardPayment
		var tmp _Alias_CreditCardPayment
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*c = CreditCardPayment(tmp)
	}

	return nil
}

type BankTransferPayment struct {
	Type           BankTransferPaymentType            `json:"type" validate:"required"`
	AccountDetails BankTransferPayment_AccountDetails `json:"accountDetails"`
}

func (b BankTransferPayment) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(b.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if v, ok := any(b.AccountDetails).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("AccountDetails", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type BankTransferPayment_AccountDetails struct {
	BankTransferPayment_AccountDetails_AnyOf *BankTransferPayment_AccountDetails_AnyOf `json:"-"`
}

func (b BankTransferPayment_AccountDetails) Validate() error {
	var errors runtime.ValidationErrors
	if b.BankTransferPayment_AccountDetails_AnyOf != nil {
		if v, ok := any(b.BankTransferPayment_AccountDetails_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BankTransferPayment_AccountDetails_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (b BankTransferPayment_AccountDetails) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(b.BankTransferPayment_AccountDetails_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("BankTransferPayment_AccountDetails_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (b *BankTransferPayment_AccountDetails) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if b.BankTransferPayment_AccountDetails_AnyOf == nil {
		b.BankTransferPayment_AccountDetails_AnyOf = &BankTransferPayment_AccountDetails_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, b.BankTransferPayment_AccountDetails_AnyOf); err != nil {
		return fmt.Errorf("BankTransferPayment_AccountDetails_AnyOf unmarshal: %w", err)
	}

	return nil
}

type DomesticAccount struct {
	AccountType   DomesticAccountAccountType `json:"accountType" validate:"required"`
	RoutingNumber string                     `json:"routingNumber" sensitive:"" validate:"required"`
	AccountNumber string                     `json:"accountNumber" sensitive:"" validate:"required"`
	AccountHolder *AccountHolder             `json:"accountHolder,omitempty"`
}

func (d DomesticAccount) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.AccountType).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("AccountType", err)
		}
	}
	if err := typesValidator.Var(d.RoutingNumber, "required"); err != nil {
		errors = errors.Append("RoutingNumber", err)
	}
	if err := typesValidator.Var(d.AccountNumber, "required"); err != nil {
		errors = errors.Append("AccountNumber", err)
	}
	if d.AccountHolder != nil {
		if v, ok := any(d.AccountHolder).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("AccountHolder", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (d DomesticAccount) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_DomesticAccount DomesticAccount
	masked := _Alias_DomesticAccount(d)
	// Mask sensitive field: RoutingNumber
	{
		maskedVal := runtime.MaskSensitiveValue(masked.RoutingNumber, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 2,
			KeepSuffix: 2,
		})
		masked.RoutingNumber = maskedVal.(string)
	}
	// Mask sensitive field: AccountNumber
	{
		maskedVal := runtime.MaskSensitiveValue(masked.AccountNumber, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 4,
		})
		masked.AccountNumber = maskedVal.(string)
	}

	return json.Marshal(masked)
}

func (d *DomesticAccount) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_DomesticAccount DomesticAccount
		var tmp _Alias_DomesticAccount
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*d = DomesticAccount(tmp)
	}

	return nil
}

type InternationalAccount struct {
	AccountType        InternationalAccountAccountType          `json:"accountType" validate:"required"`
	Iban               string                                   `json:"iban" sensitive:"" validate:"required"`
	SwiftCode          string                                   `json:"swiftCode" sensitive:"" validate:"required"`
	AccountHolder      *AccountHolder                           `json:"accountHolder,omitempty"`
	BeneficiaryDetails *InternationalAccount_BeneficiaryDetails `json:"beneficiaryDetails,omitempty"`
}

func (i InternationalAccount) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(i.AccountType).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("AccountType", err)
		}
	}
	if err := typesValidator.Var(i.Iban, "required"); err != nil {
		errors = errors.Append("Iban", err)
	}
	if err := typesValidator.Var(i.SwiftCode, "required"); err != nil {
		errors = errors.Append("SwiftCode", err)
	}
	if i.AccountHolder != nil {
		if v, ok := any(i.AccountHolder).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("AccountHolder", err)
			}
		}
	}
	if i.BeneficiaryDetails != nil {
		if v, ok := any(i.BeneficiaryDetails).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BeneficiaryDetails", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (i InternationalAccount) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_InternationalAccount InternationalAccount
	masked := _Alias_InternationalAccount(i)
	// Mask sensitive field: Iban
	{
		maskedVal := runtime.MaskSensitiveValue(masked.Iban, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 4,
			KeepSuffix: 4,
		})
		masked.Iban = maskedVal.(string)
	}
	// Mask sensitive field: SwiftCode
	{
		maskedVal := runtime.MaskSensitiveValue(masked.SwiftCode, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		masked.SwiftCode = maskedVal.(string)
	}

	return json.Marshal(masked)
}

func (i *InternationalAccount) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_InternationalAccount InternationalAccount
		var tmp _Alias_InternationalAccount
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*i = InternationalAccount(tmp)
	}

	return nil
}

type InternationalAccount_BeneficiaryDetails struct {
	InternationalAccount_BeneficiaryDetails_AnyOf *InternationalAccount_BeneficiaryDetails_AnyOf `json:"-"`
}

func (i InternationalAccount_BeneficiaryDetails) Validate() error {
	var errors runtime.ValidationErrors
	if i.InternationalAccount_BeneficiaryDetails_AnyOf != nil {
		if v, ok := any(i.InternationalAccount_BeneficiaryDetails_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("InternationalAccount_BeneficiaryDetails_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (i InternationalAccount_BeneficiaryDetails) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(i.InternationalAccount_BeneficiaryDetails_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("InternationalAccount_BeneficiaryDetails_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (i *InternationalAccount_BeneficiaryDetails) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if i.InternationalAccount_BeneficiaryDetails_AnyOf == nil {
		i.InternationalAccount_BeneficiaryDetails_AnyOf = &InternationalAccount_BeneficiaryDetails_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, i.InternationalAccount_BeneficiaryDetails_AnyOf); err != nil {
		return fmt.Errorf("InternationalAccount_BeneficiaryDetails_AnyOf unmarshal: %w", err)
	}

	return nil
}

type PersonalBeneficiary struct {
	BeneficiaryType PersonalBeneficiaryBeneficiaryType `json:"beneficiaryType" validate:"required"`
	FullName        string                             `json:"fullName" validate:"required"`
	Ssn             *string                            `json:"ssn,omitempty" sensitive:""`
	DateOfBirth     *runtime.Date                      `json:"dateOfBirth,omitempty"`
	Email           *string                            `json:"email,omitempty" sensitive:""`
	Phone           *string                            `json:"phone,omitempty" sensitive:""`
}

func (p PersonalBeneficiary) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(p.BeneficiaryType).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("BeneficiaryType", err)
		}
	}
	if err := typesValidator.Var(p.FullName, "required"); err != nil {
		errors = errors.Append("FullName", err)
	}
	if p.DateOfBirth != nil {
		if v, ok := any(p.DateOfBirth).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("DateOfBirth", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (p PersonalBeneficiary) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_PersonalBeneficiary PersonalBeneficiary
	masked := _Alias_PersonalBeneficiary(p)
	// Mask sensitive field: Ssn
	if masked.Ssn != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Ssn, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeRegex,
			Pattern:    "\\d",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Ssn = nil
		} else {
			val := maskedVal.(string)
			masked.Ssn = &val
		}
	}
	// Mask sensitive field: Email
	if masked.Email != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Email, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Email = nil
		} else {
			val := maskedVal.(string)
			masked.Email = &val
		}
	}
	// Mask sensitive field: Phone
	if masked.Phone != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Phone, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 3,
			KeepSuffix: 4,
		})
		if maskedVal == nil {
			masked.Phone = nil
		} else {
			val := maskedVal.(string)
			masked.Phone = &val
		}
	}

	return json.Marshal(masked)
}

func (p *PersonalBeneficiary) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_PersonalBeneficiary PersonalBeneficiary
		var tmp _Alias_PersonalBeneficiary
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*p = PersonalBeneficiary(tmp)
	}

	return nil
}

type BusinessBeneficiary struct {
	BeneficiaryType BusinessBeneficiaryBeneficiaryType `json:"beneficiaryType" validate:"required"`
	CompanyName     string                             `json:"companyName" validate:"required"`
	TaxID           *string                            `json:"taxId,omitempty" sensitive:""`
}

func (b BusinessBeneficiary) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(b.BeneficiaryType).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("BeneficiaryType", err)
		}
	}
	if err := typesValidator.Var(b.CompanyName, "required"); err != nil {
		errors = errors.Append("CompanyName", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (b BusinessBeneficiary) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_BusinessBeneficiary BusinessBeneficiary
	masked := _Alias_BusinessBeneficiary(b)
	// Mask sensitive field: TaxID
	if masked.TaxID != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.TaxID, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeHash,
			Pattern:    "",
			Algorithm:  "sha256",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.TaxID = nil
		} else {
			val := maskedVal.(string)
			masked.TaxID = &val
		}
	}

	return json.Marshal(masked)
}

func (b *BusinessBeneficiary) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_BusinessBeneficiary BusinessBeneficiary
		var tmp _Alias_BusinessBeneficiary
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*b = BusinessBeneficiary(tmp)
	}

	return nil
}

type DigitalWalletPayment struct {
	Type     DigitalWalletPaymentType `json:"type" validate:"required"`
	WalletID string                   `json:"walletId" sensitive:"" validate:"required"`
}

func (d DigitalWalletPayment) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.Type).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Type", err)
		}
	}
	if err := typesValidator.Var(d.WalletID, "required"); err != nil {
		errors = errors.Append("WalletID", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (d DigitalWalletPayment) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_DigitalWalletPayment DigitalWalletPayment
	masked := _Alias_DigitalWalletPayment(d)
	// Mask sensitive field: WalletID
	{
		maskedVal := runtime.MaskSensitiveValue(masked.WalletID, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeHash,
			Pattern:    "",
			Algorithm:  "sha256",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		masked.WalletID = maskedVal.(string)
	}

	return json.Marshal(masked)
}

func (d *DigitalWalletPayment) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_DigitalWalletPayment DigitalWalletPayment
		var tmp _Alias_DigitalWalletPayment
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*d = DigitalWalletPayment(tmp)
	}

	return nil
}

type Address struct {
	Street  *string `json:"street,omitempty"`
	City    *string `json:"city,omitempty"`
	ZipCode *string `json:"zipCode,omitempty"`
}

type AccountHolder struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty" sensitive:""`
}

func (a AccountHolder) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_AccountHolder AccountHolder
	masked := _Alias_AccountHolder(a)
	// Mask sensitive field: Email
	if masked.Email != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Email, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Email = nil
		} else {
			val := maskedVal.(string)
			masked.Email = &val
		}
	}

	return json.Marshal(masked)
}

func (a *AccountHolder) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_AccountHolder AccountHolder
		var tmp _Alias_AccountHolder
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*a = AccountHolder(tmp)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type PaymentMethod_AnyOf struct {
	union json.RawMessage
}

func (p *PaymentMethod_AnyOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the PaymentMethod_AnyOf as bytes
func (p *PaymentMethod_AnyOf) Raw() json.RawMessage {
	return p.union
}

// AsCreditCardPayment returns the union data inside the PaymentMethod_AnyOf as a CreditCardPayment
func (p *PaymentMethod_AnyOf) AsCreditCardPayment() (CreditCardPayment, error) {
	return UnmarshalAs[CreditCardPayment](p.union)
}

// AsValidatedCreditCardPayment returns the union data inside the PaymentMethod_AnyOf as a validated CreditCardPayment
func (p *PaymentMethod_AnyOf) AsValidatedCreditCardPayment() (CreditCardPayment, error) {
	val, err := p.AsCreditCardPayment()
	if err != nil {
		var zero CreditCardPayment
		return zero, err
	}
	if err := p.validateCreditCardPayment(val); err != nil {
		var zero CreditCardPayment
		return zero, err
	}
	return val, nil
}

// FromCreditCardPayment overwrites any union data inside the PaymentMethod_AnyOf as the provided CreditCardPayment
func (p *PaymentMethod_AnyOf) FromCreditCardPayment(val CreditCardPayment) error {
	// Validate before storing
	if err := p.validateCreditCardPayment(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsBankTransferPayment returns the union data inside the PaymentMethod_AnyOf as a BankTransferPayment
func (p *PaymentMethod_AnyOf) AsBankTransferPayment() (BankTransferPayment, error) {
	return UnmarshalAs[BankTransferPayment](p.union)
}

// AsValidatedBankTransferPayment returns the union data inside the PaymentMethod_AnyOf as a validated BankTransferPayment
func (p *PaymentMethod_AnyOf) AsValidatedBankTransferPayment() (BankTransferPayment, error) {
	val, err := p.AsBankTransferPayment()
	if err != nil {
		var zero BankTransferPayment
		return zero, err
	}
	if err := p.validateBankTransferPayment(val); err != nil {
		var zero BankTransferPayment
		return zero, err
	}
	return val, nil
}

// FromBankTransferPayment overwrites any union data inside the PaymentMethod_AnyOf as the provided BankTransferPayment
func (p *PaymentMethod_AnyOf) FromBankTransferPayment(val BankTransferPayment) error {
	// Validate before storing
	if err := p.validateBankTransferPayment(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsDigitalWalletPayment returns the union data inside the PaymentMethod_AnyOf as a DigitalWalletPayment
func (p *PaymentMethod_AnyOf) AsDigitalWalletPayment() (DigitalWalletPayment, error) {
	return UnmarshalAs[DigitalWalletPayment](p.union)
}

// AsValidatedDigitalWalletPayment returns the union data inside the PaymentMethod_AnyOf as a validated DigitalWalletPayment
func (p *PaymentMethod_AnyOf) AsValidatedDigitalWalletPayment() (DigitalWalletPayment, error) {
	val, err := p.AsDigitalWalletPayment()
	if err != nil {
		var zero DigitalWalletPayment
		return zero, err
	}
	if err := p.validateDigitalWalletPayment(val); err != nil {
		var zero DigitalWalletPayment
		return zero, err
	}
	return val, nil
}

// FromDigitalWalletPayment overwrites any union data inside the PaymentMethod_AnyOf as the provided DigitalWalletPayment
func (p *PaymentMethod_AnyOf) FromDigitalWalletPayment(val DigitalWalletPayment) error {
	// Validate before storing
	if err := p.validateDigitalWalletPayment(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// validateCreditCardPayment validates a CreditCardPayment value
func (p *PaymentMethod_AnyOf) validateCreditCardPayment(val CreditCardPayment) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateBankTransferPayment validates a BankTransferPayment value
func (p *PaymentMethod_AnyOf) validateBankTransferPayment(val BankTransferPayment) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDigitalWalletPayment validates a DigitalWalletPayment value
func (p *PaymentMethod_AnyOf) validateDigitalWalletPayment(val DigitalWalletPayment) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (p PaymentMethod_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *PaymentMethod_AnyOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}

type BankTransferPayment_AccountDetails_AnyOf struct {
	runtime.Either[DomesticAccount, InternationalAccount]
}

func (b *BankTransferPayment_AccountDetails_AnyOf) Validate() error {
	if b.IsA() {
		if v, ok := any(b.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if b.IsB() {
		if v, ok := any(b.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type InternationalAccount_BeneficiaryDetails_AnyOf struct {
	runtime.Either[PersonalBeneficiary, BusinessBeneficiary]
}

func (i *InternationalAccount_BeneficiaryDetails_AnyOf) Validate() error {
	if i.IsA() {
		if v, ok := any(i.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if i.IsB() {
		if v, ok := any(i.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
