// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetReportsIDPath struct {
	// ID The ID of the report
	ID int `json:"id" validate:"required"`
}

func (g GetReportsIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetReportsIDResponse = Report

type Report struct {
	ReportData *Report_ReportData `json:"reportData,omitempty"`
	TreeData   *Report_TreeData   `json:"treeData,omitempty"`
}

func (r Report) Validate() error {
	var errors runtime.ValidationErrors
	if r.ReportData != nil {
		if v, ok := any(r.ReportData).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ReportData", err)
			}
		}
	}
	if r.TreeData != nil {
		if v, ok := any(r.TreeData).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("TreeData", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Report_ReportData []Report_ReportData_Item

func (r Report_ReportData) Validate() error {
	if r == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range r {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Report_ReportData_Item struct {
	Name       *string                  `json:"name,omitempty"`
	Components []Report_ReportData_Item `json:"components,omitempty"`
}

func (r Report_ReportData_Item) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range r.Components {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Components[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Report_TreeData []Report_TreeData_Item

func (r Report_TreeData) Validate() error {
	if r == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range r {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Report_TreeData_Item struct {
	Value    string                 `json:"value" validate:"required,min=1"`
	Children []Report_TreeData_Item `json:"children,omitempty"`
}

func (r Report_TreeData_Item) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(r.Value, "required,min=1"); err != nil {
		errors = errors.Append("Value", err)
	}
	for i, item := range r.Children {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Children[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
