// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type CreateUserBody struct {
	User *struct {
		ID    int      `json:"id" validate:"required"`
		Score *float32 `json:"score,omitempty"`
	} `json:"user,omitempty"`
	Pages []CreateUserBodyPagesOneOf `json:"pages,omitempty"`
}

func (c CreateUserBody) Validate() error {
	return bodyTypesValidate.Struct(c)
}

type CreateUserBodyPagesAnyOf0 struct {
	Offset int `json:"offset" validate:"required"`
}

type CreateUserBodyPagesAnyOf1 struct {
	Query string `json:"query" validate:"required"`
}

type CreateUserBodyPagesOneOf0 struct {
	First  int `json:"first" validate:"required"`
	Second int `json:"second" validate:"required"`
}

type CreateUserBodyPagesOneOf1 struct {
	Last int `json:"last" validate:"required"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type CreateUserBodyPagesAnyOf struct {
	runtime.Either[CreateUserBodyPagesAnyOf0, CreateUserBodyPagesAnyOf1]
}

func (c *CreateUserBodyPagesAnyOf) MarshalJSON() ([]byte, error) {
	data := c.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (c *CreateUserBodyPagesAnyOf) UnmarshalJSON(data []byte) error {
	return c.Unmarshal(data)
}

type CreateUserBodyPagesOneOf struct {
	runtime.Either[CreateUserBodyPagesOneOf0, CreateUserBodyPagesOneOf1]
}

func (c *CreateUserBodyPagesOneOf) MarshalJSON() ([]byte, error) {
	data := c.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (c *CreateUserBodyPagesOneOf) UnmarshalJSON(data []byte) error {
	return c.Unmarshal(data)
}
