// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type CreateTestBody struct {
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type GetBaseResponse struct {
	Items *GetBase_Response_Items `json:"items,omitempty"`
}

type GetBase_Response_Items []GetBase_Response_Items_Item

type GetBase_Response_Items_Item struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
