// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Product     *OrderProductOneOf     `json:"product,omitempty"`
	Description *OrderDescriptionOneOf `json:"description,omitempty"`
	Images      []OrderImagesOneOf     `json:"images,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type VersionA = string

type VersionB = string

type VersionC = string

type VersionD = string

type VersionE = string

type OrderProductOneOf3 struct {
	Description *OrderProductOneOf3DescriptionOneOf `json:"description,omitempty"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type OrderProductOneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the OrderProductOneOf as bytes
func (o *OrderProductOneOf) Raw() json.RawMessage {
	return o.union
}

// AsVersionA returns the union data inside the OrderProductOneOf as a VersionA
func (o *OrderProductOneOf) AsVersionA() (VersionA, error) {
	return UnmarshalAs[VersionA](o.union)
}

// FromVersionA overwrites any union data inside the OrderProductOneOf as the provided VersionA
func (o *OrderProductOneOf) FromVersionA(v VersionA) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

// AsVersionB returns the union data inside the OrderProductOneOf as a VersionB
func (o *OrderProductOneOf) AsVersionB() (VersionB, error) {
	return UnmarshalAs[VersionB](o.union)
}

// FromVersionB overwrites any union data inside the OrderProductOneOf as the provided VersionB
func (o *OrderProductOneOf) FromVersionB(v VersionB) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

// AsBool returns the union data inside the OrderProductOneOf as a bool
func (o *OrderProductOneOf) AsBool() (bool, error) {
	return UnmarshalAs[bool](o.union)
}

// FromBool overwrites any union data inside the OrderProductOneOf as the provided bool
func (o *OrderProductOneOf) FromBool(v bool) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

// AsOrderProductOneOf3 returns the union data inside the OrderProductOneOf as a OrderProductOneOf3
func (o *OrderProductOneOf) AsOrderProductOneOf3() (OrderProductOneOf3, error) {
	return UnmarshalAs[OrderProductOneOf3](o.union)
}

// FromOrderProductOneOf3 overwrites any union data inside the OrderProductOneOf as the provided OrderProductOneOf3
func (o *OrderProductOneOf) FromOrderProductOneOf3(v OrderProductOneOf3) error {
	bts, err := json.Marshal(v)
	o.union = bts
	return err
}

func (o OrderProductOneOf) MarshalJSON() ([]byte, error) {
	bts, err := o.union.MarshalJSON()

	return bts, err
}

func (o *OrderProductOneOf) UnmarshalJSON(bts []byte) error {
	err := o.union.UnmarshalJSON(bts)

	return err
}

type OrderProductOneOf3DescriptionOneOf struct {
	runtime.Either[VersionC, VersionD]
}

func (o *OrderProductOneOf3DescriptionOneOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderProductOneOf3DescriptionOneOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}

type OrderDescriptionOneOf struct {
	runtime.Either[bool, string]
}

func (o *OrderDescriptionOneOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderDescriptionOneOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}

type OrderImagesOneOf struct {
	runtime.Either[string, VersionE]
}

func (o *OrderImagesOneOf) MarshalJSON() ([]byte, error) {
	data := o.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (o *OrderImagesOneOf) UnmarshalJSON(data []byte) error {
	return o.Unmarshal(data)
}
