// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type Order struct {
	Product     *Order_Product     `json:"product,omitempty"`
	Description *Order_Description `json:"description,omitempty"`
	Images      *Order_Images      `json:"images,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if o.Product != nil {
		if v, ok := any(o.Product).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Product", err)
			}
		}
	}
	if o.Description != nil {
		if v, ok := any(o.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Description", err)
			}
		}
	}
	if o.Images != nil {
		if v, ok := any(o.Images).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Images", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Product struct {
	Order_Product_OneOf *Order_Product_OneOf `json:"-"`
}

func (o Order_Product) Validate() error {
	var errors runtime.ValidationErrors
	if o.Order_Product_OneOf != nil {
		if v, ok := any(o.Order_Product_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Product_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (o Order_Product) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Product_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Product_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Product) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Product_OneOf == nil {
		o.Order_Product_OneOf = &Order_Product_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Product_OneOf); err != nil {
		return fmt.Errorf("Order_Product_OneOf unmarshal: %w", err)
	}

	return nil
}

type Order_Product_OneOf_3_Description struct {
	Order_Product_OneOf_3_Description_OneOf *Order_Product_OneOf_3_Description_OneOf `json:"-"`
}

func (o Order_Product_OneOf_3_Description) Validate() error {
	var errors runtime.ValidationErrors
	if o.Order_Product_OneOf_3_Description_OneOf != nil {
		if v, ok := any(o.Order_Product_OneOf_3_Description_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Product_OneOf_3_Description_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (o Order_Product_OneOf_3_Description) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Product_OneOf_3_Description_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Product_OneOf_3_Description_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Product_OneOf_3_Description) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Product_OneOf_3_Description_OneOf == nil {
		o.Order_Product_OneOf_3_Description_OneOf = &Order_Product_OneOf_3_Description_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Product_OneOf_3_Description_OneOf); err != nil {
		return fmt.Errorf("Order_Product_OneOf_3_Description_OneOf unmarshal: %w", err)
	}

	return nil
}

type Order_Description struct {
	Order_Description_OneOf *Order_Description_OneOf `json:"-"`
}

func (o Order_Description) Validate() error {
	var errors runtime.ValidationErrors
	if o.Order_Description_OneOf != nil {
		if v, ok := any(o.Order_Description_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Description_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (o Order_Description) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Description_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Description_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Description) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Description_OneOf == nil {
		o.Order_Description_OneOf = &Order_Description_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Description_OneOf); err != nil {
		return fmt.Errorf("Order_Description_OneOf unmarshal: %w", err)
	}

	return nil
}

type Order_Images []Order_Images_Item

func (o Order_Images) Validate() error {
	if o == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range o {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Images_Item struct {
	Order_Images_OneOf *Order_Images_OneOf `json:"-"`
}

func (o Order_Images_Item) Validate() error {
	var errors runtime.ValidationErrors
	if o.Order_Images_OneOf != nil {
		if v, ok := any(o.Order_Images_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Order_Images_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (o Order_Images_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Images_OneOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Images_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Images_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Images_OneOf == nil {
		o.Order_Images_OneOf = &Order_Images_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Images_OneOf); err != nil {
		return fmt.Errorf("Order_Images_OneOf unmarshal: %w", err)
	}

	return nil
}

type VersionA = string

type VersionB = string

type VersionC = string

type VersionD = string

type VersionE = string

type Order_Product_OneOf_3 struct {
	Description *Order_Product_OneOf_3_Description `json:"description,omitempty"`
}

func (o Order_Product_OneOf_3) Validate() error {
	var errors runtime.ValidationErrors
	if o.Description != nil {
		if v, ok := any(o.Description).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Description", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Product_OneOf struct {
	union json.RawMessage
}

func (o *Order_Product_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the Order_Product_OneOf as bytes
func (o *Order_Product_OneOf) Raw() json.RawMessage {
	return o.union
}

// AsVersionA returns the union data inside the Order_Product_OneOf as a VersionA
func (o *Order_Product_OneOf) AsVersionA() (VersionA, error) {
	return runtime.UnmarshalAs[VersionA](o.union)
}

// AsValidatedVersionA returns the union data inside the Order_Product_OneOf as a validated VersionA
func (o *Order_Product_OneOf) AsValidatedVersionA() (VersionA, error) {
	val, err := o.AsVersionA()
	if err != nil {
		var zero VersionA
		return zero, err
	}
	if err := o.validateVersionA(val); err != nil {
		var zero VersionA
		return zero, err
	}
	return val, nil
}

// FromVersionA overwrites any union data inside the Order_Product_OneOf as the provided VersionA
func (o *Order_Product_OneOf) FromVersionA(val VersionA) error {
	// Validate before storing
	if err := o.validateVersionA(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// AsVersionB returns the union data inside the Order_Product_OneOf as a VersionB
func (o *Order_Product_OneOf) AsVersionB() (VersionB, error) {
	return runtime.UnmarshalAs[VersionB](o.union)
}

// AsValidatedVersionB returns the union data inside the Order_Product_OneOf as a validated VersionB
func (o *Order_Product_OneOf) AsValidatedVersionB() (VersionB, error) {
	val, err := o.AsVersionB()
	if err != nil {
		var zero VersionB
		return zero, err
	}
	if err := o.validateVersionB(val); err != nil {
		var zero VersionB
		return zero, err
	}
	return val, nil
}

// FromVersionB overwrites any union data inside the Order_Product_OneOf as the provided VersionB
func (o *Order_Product_OneOf) FromVersionB(val VersionB) error {
	// Validate before storing
	if err := o.validateVersionB(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// AsBool returns the union data inside the Order_Product_OneOf as a bool
func (o *Order_Product_OneOf) AsBool() (bool, error) {
	return runtime.UnmarshalAs[bool](o.union)
}

// AsValidatedBool returns the union data inside the Order_Product_OneOf as a validated bool
func (o *Order_Product_OneOf) AsValidatedBool() (bool, error) {
	val, err := o.AsBool()
	if err != nil {
		var zero bool
		return zero, err
	}
	if err := o.validateBool(val); err != nil {
		var zero bool
		return zero, err
	}
	return val, nil
}

// FromBool overwrites any union data inside the Order_Product_OneOf as the provided bool
func (o *Order_Product_OneOf) FromBool(val bool) error {
	// Validate before storing
	if err := o.validateBool(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// AsOrder_Product_OneOf_3 returns the union data inside the Order_Product_OneOf as a Order_Product_OneOf_3
func (o *Order_Product_OneOf) AsOrder_Product_OneOf_3() (Order_Product_OneOf_3, error) {
	return runtime.UnmarshalAs[Order_Product_OneOf_3](o.union)
}

// AsValidatedOrder_Product_OneOf_3 returns the union data inside the Order_Product_OneOf as a validated Order_Product_OneOf_3
func (o *Order_Product_OneOf) AsValidatedOrder_Product_OneOf_3() (Order_Product_OneOf_3, error) {
	val, err := o.AsOrder_Product_OneOf_3()
	if err != nil {
		var zero Order_Product_OneOf_3
		return zero, err
	}
	if err := o.validateOrder_Product_OneOf_3(val); err != nil {
		var zero Order_Product_OneOf_3
		return zero, err
	}
	return val, nil
}

// FromOrder_Product_OneOf_3 overwrites any union data inside the Order_Product_OneOf as the provided Order_Product_OneOf_3
func (o *Order_Product_OneOf) FromOrder_Product_OneOf_3(val Order_Product_OneOf_3) error {
	// Validate before storing
	if err := o.validateOrder_Product_OneOf_3(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	o.union = bts
	return err
}

// validateVersionA validates a VersionA value
func (o *Order_Product_OneOf) validateVersionA(val VersionA) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateVersionB validates a VersionB value
func (o *Order_Product_OneOf) validateVersionB(val VersionB) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateBool validates a bool value
func (o *Order_Product_OneOf) validateBool(val bool) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateOrder_Product_OneOf_3 validates a Order_Product_OneOf_3 value
func (o *Order_Product_OneOf) validateOrder_Product_OneOf_3(val Order_Product_OneOf_3) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (o Order_Product_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := o.union.MarshalJSON()

	return bts, err
}

func (o *Order_Product_OneOf) UnmarshalJSON(bts []byte) error {
	err := o.union.UnmarshalJSON(bts)

	return err
}

type Order_Product_OneOf_3_Description_OneOf struct {
	runtime.Either[VersionC, VersionD]
}

func (o *Order_Product_OneOf_3_Description_OneOf) Validate() error {
	if o.IsA() {
		if v, ok := any(o.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if o.IsB() {
		if v, ok := any(o.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Order_Description_OneOf struct {
	runtime.Either[bool, string]
}

func (o *Order_Description_OneOf) Validate() error {
	if o.IsA() {
		if v, ok := any(o.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if o.IsB() {
		if v, ok := any(o.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Order_Images_OneOf struct {
	runtime.Either[string, VersionE]
}

func (o *Order_Images_OneOf) Validate() error {
	if o.IsA() {
		if v, ok := any(o.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if o.IsB() {
		if v, ok := any(o.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
