// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	CreateOrder(ctx context.Context, options *CreateOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateOrderResponse, error)
}

func (c *Client) CreateOrder(ctx context.Context, options *CreateOrderRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateOrderResponse, error) {
	var err error
	bodyEncoding := make(map[string]runtime.FieldEncoding)
	bodyEncoding["client_type"] = runtime.FieldEncoding{
		ContentType: "",
		Style:       "deepObject",
		Explode:     &[]bool{true}[0],
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:   c.apiClient.GetBaseURL() + "/order",
		Method:       "POST",
		Options:      options,
		ContentType:  "application/x-www-form-urlencoded",
		BodyEncoding: bodyEncoding,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateOrderResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateOrderResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/order")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)
