// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type CreateOrderBody struct {
	UserID     *string     `json:"user_id,omitempty"`
	ClientType *ClientType `json:"client_type,omitempty"`
}

func (c CreateOrderBody) Validate() error {
	return bodyTypesValidate.Struct(c)
}
