// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

type ClientType struct {
	Name    string          `json:"name" validate:"required"`
	Address *Address        `json:"address,omitempty"`
	Type    *ClientTypeType `json:"type,omitempty"`
}

func (c ClientType) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if c.Address != nil {
		if v, ok := any(c.Address).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Address", err)
			}
		}
	}
	if c.Type != nil {
		if v, ok := any(c.Type).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Type", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Address struct {
	Street string `json:"street" validate:"required"`
	City   string `json:"city" validate:"required"`
	Zip    string `json:"zip" validate:"required"`
}

func (a Address) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}
