// Code generated by oapi-codegen. DO NOT EDIT.

package xsensitivedata

import (
	"log/slog"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetUsersResponse []User

type User struct {
	ID         int64   `json:"id" validate:"required"`
	Username   string  `json:"username" validate:"required"`
	Email      *string `json:"email,omitempty" sensitive:""`
	Ssn        *string `json:"ssn,omitempty" sensitive:""`
	CreditCard *string `json:"creditCard,omitempty" sensitive:""`
	APIKey     *string `json:"apiKey,omitempty" sensitive:""`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

// Masked returns a copy of the struct with sensitive fields masked.
func (u User) Masked() User {
	masked := u
	if masked.Email != nil {
		v := runtime.MaskSensitiveString(*masked.Email, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		masked.Email = &v
	}
	if masked.Ssn != nil {
		v := runtime.MaskSensitiveString(*masked.Ssn, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeRegex,
			Pattern:    "\\d{3}-\\d{2}-\\d{4}",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		masked.Ssn = &v
	}
	if masked.CreditCard != nil {
		v := runtime.MaskSensitiveString(*masked.CreditCard, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 4,
		})
		masked.CreditCard = &v
	}
	if masked.APIKey != nil {
		v := runtime.MaskSensitiveString(*masked.APIKey, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeHash,
			Pattern:    "",
			Algorithm:  "sha256",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		masked.APIKey = &v
	}
	return masked
}

// LogValue implements slog.LogValuer interface for structured logging.
func (u User) LogValue() slog.Value {
	type plain User
	return slog.AnyValue(plain(u.Masked()))
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
