// Code generated by oapi-codegen. DO NOT EDIT.

package xsensitivedata

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetUsersResponse []User

type User struct {
	ID         int64   `json:"id" validate:"required"`
	Username   string  `json:"username" validate:"required"`
	Email      *string `json:"email,omitempty" sensitive:""`
	Ssn        *string `json:"ssn,omitempty" sensitive:""`
	CreditCard *string `json:"creditCard,omitempty" sensitive:""`
	APIKey     *string `json:"apiKey,omitempty" sensitive:""`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

func (u User) MarshalJSON() ([]byte, error) {
	// Create a copy for masking sensitive fields
	type _Alias_User User
	masked := _Alias_User(u)
	// Mask sensitive field: Email
	if masked.Email != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Email, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeFull,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Email = nil
		} else {
			val := maskedVal.(string)
			masked.Email = &val
		}
	}
	// Mask sensitive field: Ssn
	if masked.Ssn != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.Ssn, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeRegex,
			Pattern:    "\\d{3}-\\d{2}-\\d{4}",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.Ssn = nil
		} else {
			val := maskedVal.(string)
			masked.Ssn = &val
		}
	}
	// Mask sensitive field: CreditCard
	if masked.CreditCard != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.CreditCard, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypePartial,
			Pattern:    "",
			Algorithm:  "",
			KeepPrefix: 0,
			KeepSuffix: 4,
		})
		if maskedVal == nil {
			masked.CreditCard = nil
		} else {
			val := maskedVal.(string)
			masked.CreditCard = &val
		}
	}
	// Mask sensitive field: APIKey
	if masked.APIKey != nil {
		maskedVal := runtime.MaskSensitivePointer(masked.APIKey, runtime.SensitiveDataConfig{
			Type:       runtime.MaskTypeHash,
			Pattern:    "",
			Algorithm:  "sha256",
			KeepPrefix: 0,
			KeepSuffix: 0,
		})
		if maskedVal == nil {
			masked.APIKey = nil
		} else {
			val := maskedVal.(string)
			masked.APIKey = &val
		}
	}

	return json.Marshal(masked)
}

func (u *User) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_User User
		var tmp _Alias_User
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*u = User(tmp)
	}

	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
