// Code generated by oapi-codegen. DO NOT EDIT.

package multiple

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
)

// CreateBookingRequestOptions is the options needed to make a request to CreateBooking.
type CreateBookingRequestOptions struct {
	Body *CreateBookingBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateBookingRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateBookingRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *CreateBookingRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateBookingRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateBookingRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}
