// Code generated by oapi-codegen. DO NOT EDIT.

package multiple

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/google/uuid"
)

type LinksSelf struct {
	Self *string `json:"self,omitempty"`
}

type Problem struct {
	Type     *string `json:"type,omitempty"`
	Title    *string `json:"title,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

func (s Problem) Error() string {
	return "unmapped client error"
}

type Booking struct {
	ID            *uuid.UUID `json:"id,omitempty"`
	TripID        *uuid.UUID `json:"trip_id,omitempty"`
	PassengerName *string    `json:"passenger_name,omitempty"`
	HasBicycle    *bool      `json:"has_bicycle,omitempty"`
	HasDog        *bool      `json:"has_dog,omitempty"`
}

func (b Booking) Validate() error {
	var errors runtime.ValidationErrors
	if b.ID != nil {
		if v, ok := any(b.ID).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ID", err)
			}
		}
	}
	if b.TripID != nil {
		if v, ok := any(b.TripID).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("TripID", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}
