// Code generated by oapi-codegen. DO NOT EDIT.

package multiple

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type LinksSelf struct {
	Self *string `json:"self,omitempty"`
}

func (l LinksSelf) Validate() error {
	return schemaTypesValidate.Struct(l)
}

type Problem struct {
	Type     *string `json:"type,omitempty"`
	Title    *string `json:"title,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

func (p Problem) Validate() error {
	return schemaTypesValidate.Struct(p)
}

func (s Problem) Error() string {
	return "unmapped client error"
}

type Booking struct {
	ID            *uuid.UUID `json:"id,omitempty"`
	TripID        *uuid.UUID `json:"trip_id,omitempty"`
	PassengerName *string    `json:"passenger_name,omitempty"`
	HasBicycle    *bool      `json:"has_bicycle,omitempty"`
	HasDog        *bool      `json:"has_dog,omitempty"`
}

func (b Booking) Validate() error {
	return schemaTypesValidate.Struct(b)
}
