// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ResponsePredefined string

const (
	A ResponsePredefined = "A"
	B ResponsePredefined = "B"
	C ResponsePredefined = "C"
)

// Validate checks if the ResponsePredefined value is valid
func (r ResponsePredefined) Validate() error {
	switch r {
	case A, B, C:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ResponsePredefined value, got: %v", r))
	}
}

type Predefined string

const (
	A2 Predefined = "A2"
	B2 Predefined = "B2"
	C2 Predefined = "C2"
)

// Validate checks if the Predefined value is valid
func (p Predefined) Validate() error {
	switch p {
	case A2, B2, C2:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid Predefined value, got: %v", p))
	}
}

type Response struct {
	Msn1                     *MsnWithConstraints    `json:"msn1,omitempty" validate:"omitempty,max=7,min=4"`
	Msn2                     *MsnWithoutConstraints `json:"msn2,omitempty"`
	MsnReqWithConstraints    MsnWithConstraints     `json:"msn-req-with-constraints" validate:"required,max=7,min=4"`
	MsnReqWithoutConstraints MsnWithoutConstraints  `json:"msn-req-without-constraints" validate:"required"`
	Msn3                     *int                   `json:"msn3,omitempty" validate:"omitempty,gte=1,lte=100"`
	MsnFloat                 MsnFloat               `json:"msn-float" validate:"required"`
	MsnBool                  MsnBool                `json:"msn-bool"`
	MsnBoolOptional          *MsnBool               `json:"msn-bool-optional,omitempty"`
	UserRequired             User                   `json:"user-required"`
	UserOptional             *User                  `json:"user-optional,omitempty"`
	Predefined               *ResponsePredefined    `json:"predefined,omitempty"`
}

func (r Response) Validate() error {
	var errors runtime.ValidationErrors
	if r.Msn1 != nil {
		if err := typesValidator.Var(r.Msn1, "omitempty,max=7,min=4"); err != nil {
			errors = errors.Append("Msn1", err)
		}
	}
	if err := typesValidator.Var(r.MsnReqWithConstraints, "required,max=7,min=4"); err != nil {
		errors = errors.Append("MsnReqWithConstraints", err)
	}
	if err := typesValidator.Var(r.MsnReqWithoutConstraints, "required"); err != nil {
		errors = errors.Append("MsnReqWithoutConstraints", err)
	}
	if r.Msn3 != nil {
		if err := typesValidator.Var(r.Msn3, "omitempty,gte=1,lte=100"); err != nil {
			errors = errors.Append("Msn3", err)
		}
	}
	if err := typesValidator.Var(r.MsnFloat, "required"); err != nil {
		errors = errors.Append("MsnFloat", err)
	}
	if v, ok := any(r.UserRequired).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("UserRequired", err)
		}
	}
	if r.UserOptional != nil {
		if v, ok := any(r.UserOptional).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("UserOptional", err)
			}
		}
	}
	if r.Predefined != nil {
		if v, ok := any(r.Predefined).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Predefined", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type PredefinedValue struct {
	Value *Predefined `json:"value,omitempty"`
	Type  *string     `json:"type,omitempty"`
}

func (p PredefinedValue) Validate() error {
	var errors runtime.ValidationErrors
	if p.Value != nil {
		if v, ok := any(p.Value).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Value", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type MsnWithConstraints = string

type MsnWithoutConstraints = string

type MsnFloat = float32

type MsnBool = bool

type User struct {
	Name *string `json:"name,omitempty"`
	Age  *int    `json:"age,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
