// Code generated by oapi-codegen. DO NOT EDIT.

package emptyerror

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// CreateUser Create a new user
	CreateUser(ctx context.Context, options *CreateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateUserResponse, error)
}

// CreateUser Create a new user
func (c *Client) CreateUser(ctx context.Context, options *CreateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateUserResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/users",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateUserResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 201 {
			target := new(CreateUserErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateUserResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// CreateUserRequestOptions is the options needed to make a request to CreateUser.
type CreateUserRequestOptions struct {
	Body *CreateUserBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateUserRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateUserRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *CreateUserRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateUserRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateUserRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

type CreateUserBody = CreateUserRequest

type CreateUserResponse struct {
	ID       string `json:"id" validate:"required"`
	Username string `json:"username" validate:"required"`
	Email    string `json:"email" validate:"required"`
}

type CreateUserErrorResponse struct{}

func (r CreateUserErrorResponse) Error() string {
	return "unmapped client error"
}

type CreateUserErrorResponseJSON struct{}

type CreateUserErrorResponseJSON500 struct{}

type CreateUserRequest struct {
	Username string `json:"username" validate:"required"`
	Email    string `json:"email" validate:"required"`
}

func (c CreateUserRequest) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type User struct {
	ID       string `json:"id" validate:"required"`
	Username string `json:"username" validate:"required"`
	Email    string `json:"email" validate:"required"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type BadRequestException struct{}

type ConflictException struct{}

type InternalServerException struct{}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
