// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// EmailActivityResponseCommonFieldsStatus The message's status.
type EmailActivityResponseCommonFieldsStatus string

const (
	Delivered    EmailActivityResponseCommonFieldsStatus = "delivered"
	NotDelivered EmailActivityResponseCommonFieldsStatus = "not delivered"
	Processed    EmailActivityResponseCommonFieldsStatus = "processed"
)

// Validate checks if the EmailActivityResponseCommonFieldsStatus value is valid
func (e EmailActivityResponseCommonFieldsStatus) Validate() error {
	switch e {
	case Delivered, NotDelivered, Processed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid EmailActivityResponseCommonFieldsStatus value, got: %v", e))
	}
}

// GetMsgIDResponseStatus0 Quick summary of the status of a message
type GetMsgIDResponseStatus0 string

const (
	GetMsgIDResponseStatus0Delivered    GetMsgIDResponseStatus0 = "delivered"
	GetMsgIDResponseStatus0NotDelivered GetMsgIDResponseStatus0 = "not delivered"
	GetMsgIDResponseStatus0Processed    GetMsgIDResponseStatus0 = "processed"
)

// Validate checks if the GetMsgIDResponseStatus0 value is valid
func (g GetMsgIDResponseStatus0) Validate() error {
	switch g {
	case GetMsgIDResponseStatus0Delivered, GetMsgIDResponseStatus0NotDelivered, GetMsgIDResponseStatus0Processed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseStatus0 value, got: %v", g))
	}
}

// GetMsgIDResponseStatus The message's status.
type GetMsgIDResponseStatus string

const (
	GetMsgIDResponseStatusDelivered    GetMsgIDResponseStatus = "delivered"
	GetMsgIDResponseStatusNotDelivered GetMsgIDResponseStatus = "not delivered"
	GetMsgIDResponseStatusProcessed    GetMsgIDResponseStatus = "processed"
)

// Validate checks if the GetMsgIDResponseStatus value is valid
func (g GetMsgIDResponseStatus) Validate() error {
	switch g {
	case GetMsgIDResponseStatusDelivered, GetMsgIDResponseStatusNotDelivered, GetMsgIDResponseStatusProcessed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseStatus value, got: %v", g))
	}
}

// GetMsgIDResponseEventsBounceType0 Use to distinguish between types of bounces
type GetMsgIDResponseEventsBounceType0 string

const (
	Blocked GetMsgIDResponseEventsBounceType0 = "blocked"
	Bounced GetMsgIDResponseEventsBounceType0 = "bounced"
	Expired GetMsgIDResponseEventsBounceType0 = "expired"
)

// Validate checks if the GetMsgIDResponseEventsBounceType0 value is valid
func (g GetMsgIDResponseEventsBounceType0) Validate() error {
	switch g {
	case Blocked, Bounced, Expired:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseEventsBounceType0 value, got: %v", g))
	}
}

// GetMsgIDResponseEventsBounceType Use to distinguish between types of bounces
type GetMsgIDResponseEventsBounceType string

const (
	Hard GetMsgIDResponseEventsBounceType = "hard"
	Soft GetMsgIDResponseEventsBounceType = "soft"
)

// Validate checks if the GetMsgIDResponseEventsBounceType value is valid
func (g GetMsgIDResponseEventsBounceType) Validate() error {
	switch g {
	case Hard, Soft:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetMsgIDResponseEventsBounceType value, got: %v", g))
	}
}

type GetMsgIDResponse struct {
	// Status The message's status.
	Status *GetMsgIDResponseStatus `json:"status,omitempty"`

	// Events List of events related to email message
	Events *GetMsgID_Response_Events `json:"events,omitempty"`
}

type EmailActivityResponseCommonFields struct {
	// Status The message's status.
	Status *EmailActivityResponseCommonFieldsStatus `json:"status,omitempty"`
}

func (e EmailActivityResponseCommonFields) Validate() error {
	var errors runtime.ValidationErrors
	if e.Status != nil {
		if v, ok := any(e.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// GetMsgID_Response_Events0 List of events related to email message
type GetMsgID_Response_Events0 []GetMsgID_Response_Events_Item0

func (g GetMsgID_Response_Events0) Validate() error {
	if g == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range g {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetMsgID_Response_Events_Item0 struct {
	// BounceType Use to distinguish between types of bounces
	BounceType *GetMsgIDResponseEventsBounceType0 `json:"bounce_type,omitempty"`
}

func (g GetMsgID_Response_Events_Item0) Validate() error {
	var errors runtime.ValidationErrors
	if g.BounceType != nil {
		if v, ok := any(g.BounceType).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BounceType", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// GetMsgID_Response_Events List of events related to email message
type GetMsgID_Response_Events []GetMsgID_Response_Events_Item

func (g GetMsgID_Response_Events) Validate() error {
	if g == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range g {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetMsgID_Response_Events_Item struct {
	// BounceType Use to distinguish between types of bounces
	BounceType *GetMsgIDResponseEventsBounceType `json:"bounce_type,omitempty"`
}

func (g GetMsgID_Response_Events_Item) Validate() error {
	var errors runtime.ValidationErrors
	if g.BounceType != nil {
		if v, ok := any(g.BounceType).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("BounceType", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
