// Code generated by oapi-codegen. DO NOT EDIT.

package gen

type ResponsePredefined string

const (
	A ResponsePredefined = "A"
	B ResponsePredefined = "B"
	C ResponsePredefined = "C"
)

type Predefined string

const (
	A2 Predefined = "A2"
	B2 Predefined = "B2"
	C2 Predefined = "C2"
)

type Response struct {
	Msn1                     *MsnWithConstraints    `json:"msn1,omitempty"`
	Msn2                     *MsnWithoutConstraints `json:"msn2,omitempty"`
	MsnReqWithConstraints    MsnWithConstraints     `json:"msn-req-with-constraints"`
	MsnReqWithoutConstraints MsnWithoutConstraints  `json:"msn-req-without-constraints"`
	Msn3                     *int                   `json:"msn3,omitempty"`
	MsnFloat                 MsnFloat               `json:"msn-float"`
	MsnBool                  MsnBool                `json:"msn-bool"`
	MsnBoolOptional          *MsnBool               `json:"msn-bool-optional,omitempty"`
	UserRequired             User                   `json:"user-required"`
	UserOptional             *User                  `json:"user-optional,omitempty"`
	Predefined               *ResponsePredefined    `json:"predefined,omitempty"`
}

type PredefinedValue struct {
	Value *Predefined `json:"value,omitempty"`
	Type  *string     `json:"type,omitempty"`
}

type MsnWithConstraints = string

type MsnWithoutConstraints = string

type MsnFloat = float32

type MsnBool = bool

type User struct {
	Name *string `json:"name,omitempty"`
	Age  *int    `json:"age,omitempty"`
}
