// Code generated by oapi-codegen. DO NOT EDIT.

package client

type GetClientResponseType string

const (
	GetClientResponseTypeCompany    GetClientResponseType = "company"
	GetClientResponseTypeIndividual GetClientResponseType = "individual"
)

type ClientTypeType string

const (
	ClientTypeTypeCompany    ClientTypeType = "company"
	ClientTypeTypeIndividual ClientTypeType = "individual"
)
