openapi: "3.0.0"
info:
  version: 1.0.0
  title: Generate models
paths:
  /client:
    parameters:
      - $ref: "#/components/parameters/Merchant-Serial-Number"
    get:
      operationId: getClient
      description: "getClient description"
      summary: "getClient summary"
      responses:
        200:
          description: Success response description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientType"
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Error response.
    put:
      operationId: updateClient
      description: "updateClient description"
      summary: "updateClient summary"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/ClientType"
      responses:
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: "Error code description"
                required:
                - code
components:
  schemas:
    ClientType:
      type: object
      description: "Client type description"
      required:
        - name
      properties:
        name:
          type: string
          description: "Client name description"
        type:
          type: string
          description: "Client type description"
          enum:
            - "individual"
            - "company"
    # NOTE that this is not generated by default because it's not referenced.
    # If you want it, you need to use the following YAML configuration:
    #
    # skip-prune: true
    Unreferenced:
      type: object
      required:
        - id
      properties:
        id:
          type: integer

    MSN:
      type: string
      title: MSNType
      pattern: ^[0-9]{4,7}$
      minLength: 4
      maxLength: 7
      example: '1234567'
      description: The merchant serial number (MSN) for the sales unit.

    error:
      type: object
      properties:
        code:
          type: string
          description: "Error code description"
        message:
          type: string
          description: "Error message description"

  parameters:
    Merchant-Serial-Number:
      name: Merchant-Serial-Number
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/MSN'
