// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type CreateUserBody struct {
	User  *CreateUserBody_User  `json:"user,omitempty"`
	Pages *CreateUserBody_Pages `json:"pages,omitempty"`
}

func (c CreateUserBody) Validate() error {
	var errors runtime.ValidationErrors
	if c.User != nil {
		if v, ok := any(c.User).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("User", err)
			}
		}
	}
	if c.Pages != nil {
		if v, ok := any(c.Pages).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Pages", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateUserBody_User struct {
	ID    int      `json:"id" validate:"required"`
	Score *float32 `json:"score,omitempty"`
}

func (c CreateUserBody_User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type CreateUserBody_Pages []CreateUserBody_Pages_Item

func (c CreateUserBody_Pages) Validate() error {
	if c == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range c {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateUserBody_Pages_Item struct {
	Limit                      int                         `json:"limit" validate:"required"`
	Tag1                       *string                     `json:"tag1,omitempty"`
	Tag2                       *string                     `json:"tag2,omitempty"`
	CreateUserBody_Pages_AnyOf *CreateUserBody_Pages_AnyOf `json:"-"`
	CreateUserBody_Pages_OneOf *CreateUserBody_Pages_OneOf `json:"-"`
}

func (c CreateUserBody_Pages_Item) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(c.Limit, "required"); err != nil {
		errors = errors.Append("Limit", err)
	}
	if c.CreateUserBody_Pages_AnyOf != nil {
		if v, ok := any(c.CreateUserBody_Pages_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CreateUserBody_Pages_AnyOf", err)
			}
		}
	}
	if c.CreateUserBody_Pages_OneOf != nil {
		if v, ok := any(c.CreateUserBody_Pages_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CreateUserBody_Pages_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c CreateUserBody_Pages_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	type _Alias_CreateUserBody_Pages_Item CreateUserBody_Pages_Item
	baseJSON, err := json.Marshal((_Alias_CreateUserBody_Pages_Item)(c))
	if err != nil {
		return nil, err
	}
	parts = append(parts, baseJSON)

	{
		b, err := runtime.MarshalJSON(c.CreateUserBody_Pages_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("CreateUserBody_Pages_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(c.CreateUserBody_Pages_OneOf)
		if err != nil {
			return nil, fmt.Errorf("CreateUserBody_Pages_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *CreateUserBody_Pages_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if len(trim) > 0 {
		type _Alias_CreateUserBody_Pages_Item CreateUserBody_Pages_Item
		var tmp _Alias_CreateUserBody_Pages_Item
		if err := json.Unmarshal(data, &tmp); err != nil {
			return err
		}
		*c = CreateUserBody_Pages_Item(tmp)
	}

	if c.CreateUserBody_Pages_AnyOf == nil {
		c.CreateUserBody_Pages_AnyOf = &CreateUserBody_Pages_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.CreateUserBody_Pages_AnyOf); err != nil {
		return fmt.Errorf("CreateUserBody_Pages_AnyOf unmarshal: %w", err)
	}

	if c.CreateUserBody_Pages_OneOf == nil {
		c.CreateUserBody_Pages_OneOf = &CreateUserBody_Pages_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.CreateUserBody_Pages_OneOf); err != nil {
		return fmt.Errorf("CreateUserBody_Pages_OneOf unmarshal: %w", err)
	}

	return nil
}

type CreateUserBody_Pages_AnyOf_0 struct {
	Offset int `json:"offset" validate:"required"`
}

func (c CreateUserBody_Pages_AnyOf_0) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type CreateUserBody_Pages_AnyOf_1 struct {
	Query string `json:"query" validate:"required"`
}

func (c CreateUserBody_Pages_AnyOf_1) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type CreateUserBody_Pages_OneOf_0 struct {
	First  int `json:"first" validate:"required"`
	Second int `json:"second" validate:"required"`
}

func (c CreateUserBody_Pages_OneOf_0) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type CreateUserBody_Pages_OneOf_1 struct {
	Last int `json:"last" validate:"required"`
}

func (c CreateUserBody_Pages_OneOf_1) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type CreateUserBody_Pages_AnyOf struct {
	runtime.Either[CreateUserBody_Pages_AnyOf_0, CreateUserBody_Pages_AnyOf_1]
}

func (c *CreateUserBody_Pages_AnyOf) Validate() error {
	if c.IsA() {
		if v, ok := any(c.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if c.IsB() {
		if v, ok := any(c.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type CreateUserBody_Pages_OneOf struct {
	runtime.Either[CreateUserBody_Pages_OneOf_0, CreateUserBody_Pages_OneOf_1]
}

func (c *CreateUserBody_Pages_OneOf) Validate() error {
	if c.IsA() {
		if v, ok := any(c.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if c.IsB() {
		if v, ok := any(c.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
