// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetTest(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetTestResponse, error)
}

func (c *Client) GetTest(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetTestResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/test",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetTestResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetTestResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/test")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

type GetTestResponse struct {
	Params *GetTest_Response_Params `json:"params,omitempty"`
}

type GetTest_Response_Params struct {
	Required *GetTest_Response_Params_Required `json:"required,omitempty"`
}

func (g GetTest_Response_Params) Validate() error {
	var errors runtime.ValidationErrors
	if g.Required != nil {
		if v, ok := any(g.Required).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Required", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetTest_Response_Params_Required [][][]GetTest_Response_Params_Required_Item

type GetTest_Response_Params_Required_Item struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
