// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error)
}

func (c *Client) GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/files",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetFilesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetFilesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/files")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

type FileObject string

const (
	FileObjectFile FileObject = "file"
)

// Validate checks if the FileObject value is valid
func (f FileObject) Validate() error {
	switch f {
	case FileObjectFile:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FileObject value, got: %v", f))
	}
}

type FilePurpose string

const (
	AccountRequirement     FilePurpose = "account_requirement"
	AdditionalVerification FilePurpose = "additional_verification"
	BusinessIcon           FilePurpose = "business_icon"
)

// Validate checks if the FilePurpose value is valid
func (f FilePurpose) Validate() error {
	switch f {
	case AccountRequirement, AdditionalVerification, BusinessIcon:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FilePurpose value, got: %v", f))
	}
}

type FileLinksObject string

const (
	List FileLinksObject = "list"
)

// Validate checks if the FileLinksObject value is valid
func (f FileLinksObject) Validate() error {
	switch f {
	case List:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FileLinksObject value, got: %v", f))
	}
}

type FileLinkObject string

const (
	FileLinkObjectFileLink FileLinkObject = "file_link"
)

// Validate checks if the FileLinkObject value is valid
func (f FileLinkObject) Validate() error {
	switch f {
	case FileLinkObjectFileLink:
		return nil
	default:
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid FileLinkObject value, got: %v", f))
	}
}

type GetFilesResponse GetFiles_Response

type File struct {
	Filename *string      `json:"filename,omitempty" validate:"omitempty,max=5000"`
	ID       string       `json:"id" validate:"required,max=5000"`
	Author   *File_Author `json:"author,omitempty"`
	Links    *File_Links  `json:"links,omitempty"`
	Object   FileObject   `json:"object" validate:"required"`
	Purpose  FilePurpose  `json:"purpose" validate:"required"`
	Size     int          `json:"size" validate:"required"`
	Title    *string      `json:"title,omitempty" validate:"omitempty,max=5000"`
}

func (f File) Validate() error {
	var errors runtime.ValidationErrors
	if f.Filename != nil {
		if err := typesValidator.Var(f.Filename, "omitempty,max=5000"); err != nil {
			errors = errors.Append("Filename", err)
		}
	}
	if err := typesValidator.Var(f.ID, "required,max=5000"); err != nil {
		errors = errors.Append("ID", err)
	}
	if f.Author != nil {
		if v, ok := any(f.Author).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Author", err)
			}
		}
	}
	if f.Links != nil {
		if v, ok := any(f.Links).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Links", err)
			}
		}
	}
	if v, ok := any(f.Object).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Object", err)
		}
	}
	if v, ok := any(f.Purpose).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Purpose", err)
		}
	}
	if err := typesValidator.Var(f.Size, "required"); err != nil {
		errors = errors.Append("Size", err)
	}
	if f.Title != nil {
		if err := typesValidator.Var(f.Title, "omitempty,max=5000"); err != nil {
			errors = errors.Append("Title", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type File_Author struct {
	File_Author_AnyOf *File_Author_AnyOf `json:"-"`
}

func (f File_Author) Validate() error {
	var errors runtime.ValidationErrors
	if f.File_Author_AnyOf != nil {
		if v, ok := any(f.File_Author_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("File_Author_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (f File_Author) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(f.File_Author_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("File_Author_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (f *File_Author) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if f.File_Author_AnyOf == nil {
		f.File_Author_AnyOf = &File_Author_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, f.File_Author_AnyOf); err != nil {
		return fmt.Errorf("File_Author_AnyOf unmarshal: %w", err)
	}

	return nil
}

type File_Links struct {
	Data    []FileLink      `json:"data" validate:"required"`
	HasMore bool            `json:"has_more"`
	Object  FileLinksObject `json:"object" validate:"required"`
	URL     string          `json:"url" validate:"required,max=5000"`
}

func (f File_Links) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(f.Data, "required"); err != nil {
		errors = errors.Append("Data", err)
	}
	if v, ok := any(f.Object).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Object", err)
		}
	}
	if err := typesValidator.Var(f.URL, "required,max=5000"); err != nil {
		errors = errors.Append("URL", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type FileLink struct {
	Created  int               `json:"created" validate:"required"`
	File     FileLink_File     `json:"file"`
	ID       string            `json:"id" validate:"required,max=5000"`
	Livemode *bool             `json:"livemode,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Object   *FileLinkObject   `json:"object,omitempty"`
	URL      *string           `json:"url,omitempty" validate:"omitempty,max=5000"`
}

func (f FileLink) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(f.Created, "required"); err != nil {
		errors = errors.Append("Created", err)
	}
	if v, ok := any(f.File).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("File", err)
		}
	}
	if err := typesValidator.Var(f.ID, "required,max=5000"); err != nil {
		errors = errors.Append("ID", err)
	}
	if f.Object != nil {
		if v, ok := any(f.Object).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Object", err)
			}
		}
	}
	if f.URL != nil {
		if err := typesValidator.Var(f.URL, "omitempty,max=5000"); err != nil {
			errors = errors.Append("URL", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type FileLink_File struct {
	FileLink_File_AnyOf *FileLink_File_AnyOf `json:"-"`
}

func (f FileLink_File) Validate() error {
	var errors runtime.ValidationErrors
	if f.FileLink_File_AnyOf != nil {
		if v, ok := any(f.FileLink_File_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("FileLink_File_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (f FileLink_File) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(f.FileLink_File_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("FileLink_File_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (f *FileLink_File) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if f.FileLink_File_AnyOf == nil {
		f.FileLink_File_AnyOf = &FileLink_File_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, f.FileLink_File_AnyOf); err != nil {
		return fmt.Errorf("FileLink_File_AnyOf unmarshal: %w", err)
	}

	return nil
}

type User struct {
	ID     string       `json:"id" validate:"required,max=50"`
	Avatar *User_Avatar `json:"avatar,omitempty"`
}

func (u User) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(u.ID, "required,max=50"); err != nil {
		errors = errors.Append("ID", err)
	}
	if u.Avatar != nil {
		if v, ok := any(u.Avatar).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Avatar", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type User_Avatar struct {
	User_Avatar_AnyOf *User_Avatar_AnyOf `json:"-"`
}

func (u User_Avatar) Validate() error {
	var errors runtime.ValidationErrors
	if u.User_Avatar_AnyOf != nil {
		if v, ok := any(u.User_Avatar_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("User_Avatar_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (u User_Avatar) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(u.User_Avatar_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("User_Avatar_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (u *User_Avatar) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if u.User_Avatar_AnyOf == nil {
		u.User_Avatar_AnyOf = &User_Avatar_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, u.User_Avatar_AnyOf); err != nil {
		return fmt.Errorf("User_Avatar_AnyOf unmarshal: %w", err)
	}

	return nil
}

type GetFiles_Response []GetFiles_Response_Item

func (g GetFiles_Response) Validate() error {
	if g == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range g {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetFiles_Response_Item struct {
	GetFiles_Response_OneOf *GetFiles_Response_OneOf `json:"-"`
}

func (g GetFiles_Response_Item) Validate() error {
	var errors runtime.ValidationErrors
	if g.GetFiles_Response_OneOf != nil {
		if v, ok := any(g.GetFiles_Response_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("GetFiles_Response_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (g GetFiles_Response_Item) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetFiles_Response_OneOf)
		if err != nil {
			return nil, fmt.Errorf("GetFiles_Response_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetFiles_Response_Item) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetFiles_Response_OneOf == nil {
		g.GetFiles_Response_OneOf = &GetFiles_Response_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetFiles_Response_OneOf); err != nil {
		return fmt.Errorf("GetFiles_Response_OneOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type File_Author_AnyOf struct {
	runtime.Either[User, string]
}

func (f *File_Author_AnyOf) Validate() error {
	if f.IsA() {
		if v, ok := any(f.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if f.IsB() {
		if err := typesValidator.Var(f.B, "max=50"); err != nil {
			return err
		}
	}
	return nil
}

type FileLink_File_AnyOf struct {
	runtime.Either[string, File]
}

func (f *FileLink_File_AnyOf) Validate() error {
	if f.IsA() {
		if err := typesValidator.Var(f.A, "max=5000"); err != nil {
			return err
		}
	}
	if f.IsB() {
		if v, ok := any(f.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type User_Avatar_AnyOf struct {
	runtime.Either[File, string]
}

func (u *User_Avatar_AnyOf) Validate() error {
	if u.IsA() {
		if v, ok := any(u.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if u.IsB() {
		if err := typesValidator.Var(u.B, "max=50"); err != nil {
			return err
		}
	}
	return nil
}

type GetFiles_Response_OneOf struct {
	runtime.Either[string, File]
}

func (g *GetFiles_Response_OneOf) Validate() error {
	if g.IsA() {
		if v, ok := any(g.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if g.IsB() {
		if v, ok := any(g.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
