// Code generated by oapi-codegen. DO NOT EDIT.

package circularmutual

import (
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type FileObject string

const (
	FileObjectFile FileObject = "file"
)

type FilePurpose string

const (
	FilePurposeAccountRequirement     FilePurpose = "account_requirement"
	FilePurposeAdditionalVerification FilePurpose = "additional_verification"
	FilePurposeBusinessIcon           FilePurpose = "business_icon"
)

type FileLinksObject string

const (
	FileLinksObjectList FileLinksObject = "list"
)

type FileLinkObject string

const (
	FileLinkObjectFileLink FileLinkObject = "file_link"
)

type GetFilesResponse []GetFilesResponseOneOf

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type File struct {
	Filename *string          `json:"filename,omitempty" validate:"omitempty,max=5000"`
	ID       string           `json:"id" validate:"required,max=5000"`
	Author   *FileAuthorAnyOf `json:"author,omitempty"`
	Links    *struct {
		Data    []FileLink      `json:"data" validate:"required"`
		HasMore bool            `json:"has_more"`
		Object  FileLinksObject `json:"object" validate:"required"`
		URL     string          `json:"url" validate:"required,max=5000"`
	} `json:"links,omitempty"`
	Object  FileObject  `json:"object" validate:"required"`
	Purpose FilePurpose `json:"purpose" validate:"required"`
	Size    int         `json:"size" validate:"required"`
	Title   *string     `json:"title,omitempty" validate:"omitempty,max=5000"`
}

func (f File) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type FileLink struct {
	Created  int               `json:"created" validate:"required"`
	File     FileLinkFileAnyOf `json:"file" validate:"required"`
	ID       string            `json:"id" validate:"required,max=5000"`
	Livemode *bool             `json:"livemode,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Object   *FileLinkObject   `json:"object,omitempty"`
	URL      *string           `json:"url,omitempty" validate:"omitempty,max=5000"`
}

func (f FileLink) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type User struct {
	ID     string           `json:"id" validate:"required,max=50"`
	Avatar *UserAvatarAnyOf `json:"avatar,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type FileAuthorAnyOf struct {
	runtime.Either[User, string]
}

func (f *FileAuthorAnyOf) MarshalJSON() ([]byte, error) {
	data := f.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (f *FileAuthorAnyOf) UnmarshalJSON(data []byte) error {
	return f.Unmarshal(data)
}

type FileLinkFileAnyOf struct {
	runtime.Either[string, File]
}

func (f *FileLinkFileAnyOf) MarshalJSON() ([]byte, error) {
	data := f.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (f *FileLinkFileAnyOf) UnmarshalJSON(data []byte) error {
	return f.Unmarshal(data)
}

type UserAvatarAnyOf struct {
	runtime.Either[File, string]
}

func (u *UserAvatarAnyOf) MarshalJSON() ([]byte, error) {
	data := u.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (u *UserAvatarAnyOf) UnmarshalJSON(data []byte) error {
	return u.Unmarshal(data)
}

type GetFilesResponseOneOf struct {
	runtime.Either[string, File]
}

func (g *GetFilesResponseOneOf) MarshalJSON() ([]byte, error) {
	data := g.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (g *GetFilesResponseOneOf) UnmarshalJSON(data []byte) error {
	return g.Unmarshal(data)
}
