// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error)
}

func (c *Client) GetFiles(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetFilesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/files",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetFilesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetFilesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/files")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

type FileObject string

const (
	FileObjectFile FileObject = "file"
)

type FilePurpose string

const (
	AccountRequirement     FilePurpose = "account_requirement"
	AdditionalVerification FilePurpose = "additional_verification"
	BusinessIcon           FilePurpose = "business_icon"
)

type FileLinksObject string

const (
	List FileLinksObject = "list"
)

type FileLinkObject string

const (
	FileLinkObjectFileLink FileLinkObject = "file_link"
)

type GetFilesResponse []GetFiles_Response

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type File struct {
	Filename *string      `json:"filename,omitempty" validate:"omitempty,max=5000"`
	ID       string       `json:"id" validate:"required,max=5000"`
	Author   *File_Author `json:"author,omitempty"`
	Links    *File_Links  `json:"links,omitempty"`
	Object   FileObject   `json:"object" validate:"required"`
	Purpose  FilePurpose  `json:"purpose" validate:"required"`
	Size     int          `json:"size" validate:"required"`
	Title    *string      `json:"title,omitempty" validate:"omitempty,max=5000"`
}

func (f File) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type File_Author struct {
	File_Author_AnyOf *File_Author_AnyOf `json:"-"`
}

func (f File_Author) Validate() error {
	return schemaTypesValidate.Struct(f)
}

func (f File_Author) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(f.File_Author_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("File_Author_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (f *File_Author) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if f.File_Author_AnyOf == nil {
		f.File_Author_AnyOf = &File_Author_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, f.File_Author_AnyOf); err != nil {
		return fmt.Errorf("File_Author_AnyOf unmarshal: %w", err)
	}

	return nil
}

type File_Links struct {
	Data    []FileLink      `json:"data" validate:"required"`
	HasMore bool            `json:"has_more"`
	Object  FileLinksObject `json:"object" validate:"required"`
	URL     string          `json:"url" validate:"required,max=5000"`
}

func (f File_Links) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type FileLink struct {
	Created  int               `json:"created" validate:"required"`
	File     FileLink_File     `json:"file" validate:"required"`
	ID       string            `json:"id" validate:"required,max=5000"`
	Livemode *bool             `json:"livemode,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	Object   *FileLinkObject   `json:"object,omitempty"`
	URL      *string           `json:"url,omitempty" validate:"omitempty,max=5000"`
}

func (f FileLink) Validate() error {
	return schemaTypesValidate.Struct(f)
}

type FileLink_File struct {
	FileLink_File_AnyOf *FileLink_File_AnyOf `json:"-"`
}

func (f FileLink_File) Validate() error {
	return schemaTypesValidate.Struct(f)
}

func (f FileLink_File) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(f.FileLink_File_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("FileLink_File_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (f *FileLink_File) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if f.FileLink_File_AnyOf == nil {
		f.FileLink_File_AnyOf = &FileLink_File_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, f.FileLink_File_AnyOf); err != nil {
		return fmt.Errorf("FileLink_File_AnyOf unmarshal: %w", err)
	}

	return nil
}

type User struct {
	ID     string       `json:"id" validate:"required,max=50"`
	Avatar *User_Avatar `json:"avatar,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}

type User_Avatar struct {
	User_Avatar_AnyOf *User_Avatar_AnyOf `json:"-"`
}

func (u User_Avatar) Validate() error {
	return schemaTypesValidate.Struct(u)
}

func (u User_Avatar) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(u.User_Avatar_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("User_Avatar_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (u *User_Avatar) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if u.User_Avatar_AnyOf == nil {
		u.User_Avatar_AnyOf = &User_Avatar_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, u.User_Avatar_AnyOf); err != nil {
		return fmt.Errorf("User_Avatar_AnyOf unmarshal: %w", err)
	}

	return nil
}

type GetFiles_Response struct {
	GetFiles_Response_OneOf *GetFiles_Response_OneOf `json:"-"`
}

func (g GetFiles_Response) Validate() error {
	return schemaTypesValidate.Struct(g)
}

func (g GetFiles_Response) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(g.GetFiles_Response_OneOf)
		if err != nil {
			return nil, fmt.Errorf("GetFiles_Response_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (g *GetFiles_Response) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if g.GetFiles_Response_OneOf == nil {
		g.GetFiles_Response_OneOf = &GetFiles_Response_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, g.GetFiles_Response_OneOf); err != nil {
		return fmt.Errorf("GetFiles_Response_OneOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type File_Author_AnyOf struct {
	runtime.Either[User, string]
}

type FileLink_File_AnyOf struct {
	runtime.Either[string, File]
}

type User_Avatar_AnyOf struct {
	runtime.Either[File, string]
}

type GetFiles_Response_OneOf struct {
	runtime.Either[string, File]
}
