// Code generated by oapi-codegen. DO NOT EDIT.

package optionalproperties

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// PostPayments Start a transaction
	PostPayments(ctx context.Context, options *PostPaymentsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PostPaymentsResponse, error)
}

// PostPayments Start a transaction
func (c *Client) PostPayments(ctx context.Context, options *PostPaymentsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PostPaymentsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/payments",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*PostPaymentsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(PostPaymentsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/payments")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())

// PostPaymentsRequestOptions is the options needed to make a request to PostPayments.
type PostPaymentsRequestOptions struct {
	Body *PostPaymentsBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *PostPaymentsRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if err := clientOptionsValidate.Struct(o.Body); err != nil {
		errors = append(errors, runtime.NewValidationErrorsFromErrors("Body", []error{err})...)
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *PostPaymentsRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *PostPaymentsRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *PostPaymentsRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *PostPaymentsRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

func asMap[V any](v any) (map[string]V, error) {
	if v == nil {
		return nil, nil
	}
	res, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]V
	err = json.Unmarshal(res, &m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type PostPaymentsBody = Purchase

type PostPaymentsResponse = string

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Purchase struct {
	User *User `json:"user,omitempty"`
}

func (p Purchase) Validate() error {
	return schemaTypesValidate.Struct(p)
}

type User struct {
	Name *string `json:"name,omitempty"`
}

func (u User) Validate() error {
	return schemaTypesValidate.Struct(u)
}
