// Code generated by oapi-codegen. DO NOT EDIT.

package xenumnames

type ClientType string

const (
	ACT ClientType = "ACT"
	EXP ClientType = "EXP"
)

type ClientTypeWithNamesExtension string

const (
	Active  ClientTypeWithNamesExtension = "ACT"
	Expired ClientTypeWithNamesExtension = "EXP"
)
