// Code generated by oapi-codegen. DO NOT EDIT.

package oneof

import (
	"encoding/json"
	"fmt"

	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ProcessPaymentBody = ProcessPaymentBodyOneOf

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ResponseA struct {
	A *string `json:"a,omitempty"`
}

func (r ResponseA) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseB struct {
	B *string `json:"b,omitempty"`
}

func (r ResponseB) Validate() error {
	return schemaTypesValidate.Struct(r)
}

type ResponseC struct {
	C *string `json:"c,omitempty"`
}

func (r ResponseC) Validate() error {
	return schemaTypesValidate.Struct(r)
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPaymentBodyOneOf struct {
	union json.RawMessage
}

// Raw returns the union data inside the ProcessPaymentBodyOneOf as bytes
func (p *ProcessPaymentBodyOneOf) Raw() json.RawMessage {
	return p.union
}

// AsResponseA returns the union data inside the ProcessPaymentBodyOneOf as a ResponseA
func (p *ProcessPaymentBodyOneOf) AsResponseA() (ResponseA, error) {
	return UnmarshalAs[ResponseA](p.union)
}

// FromResponseA overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseA
func (p *ProcessPaymentBodyOneOf) FromResponseA(v ResponseA) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseB returns the union data inside the ProcessPaymentBodyOneOf as a ResponseB
func (p *ProcessPaymentBodyOneOf) AsResponseB() (ResponseB, error) {
	return UnmarshalAs[ResponseB](p.union)
}

// FromResponseB overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseB
func (p *ProcessPaymentBodyOneOf) FromResponseB(v ResponseB) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

// AsResponseC returns the union data inside the ProcessPaymentBodyOneOf as a ResponseC
func (p *ProcessPaymentBodyOneOf) AsResponseC() (ResponseC, error) {
	return UnmarshalAs[ResponseC](p.union)
}

// FromResponseC overwrites any union data inside the ProcessPaymentBodyOneOf as the provided ResponseC
func (p *ProcessPaymentBodyOneOf) FromResponseC(v ResponseC) error {
	bts, err := json.Marshal(v)
	p.union = bts
	return err
}

func (p ProcessPaymentBodyOneOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProcessPaymentBodyOneOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}
