// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ProcessPaymentBody struct {
	ProcessPaymentBody_OneOf *ProcessPaymentBody_OneOf `json:"-"`
}

func (p ProcessPaymentBody) Validate() error {
	var errors runtime.ValidationErrors
	if p.ProcessPaymentBody_OneOf != nil {
		if v, ok := any(p.ProcessPaymentBody_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ProcessPaymentBody_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (p ProcessPaymentBody) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProcessPaymentBody_OneOf)
		if err != nil {
			return nil, fmt.Errorf("ProcessPaymentBody_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProcessPaymentBody) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProcessPaymentBody_OneOf == nil {
		p.ProcessPaymentBody_OneOf = &ProcessPaymentBody_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProcessPaymentBody_OneOf); err != nil {
		return fmt.Errorf("ProcessPaymentBody_OneOf unmarshal: %w", err)
	}

	return nil
}

type PayloadA struct {
	A *string `json:"a,omitempty"`
}

type PayloadB struct {
	B *string `json:"b,omitempty"`
}

type PayloadC struct {
	C *string `json:"c,omitempty"`
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ProcessPaymentBody_OneOf struct {
	union json.RawMessage
}

func (p *ProcessPaymentBody_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the ProcessPaymentBody_OneOf as bytes
func (p *ProcessPaymentBody_OneOf) Raw() json.RawMessage {
	return p.union
}

// AsPayloadA returns the union data inside the ProcessPaymentBody_OneOf as a PayloadA
func (p *ProcessPaymentBody_OneOf) AsPayloadA() (PayloadA, error) {
	return UnmarshalAs[PayloadA](p.union)
}

// AsValidatedPayloadA returns the union data inside the ProcessPaymentBody_OneOf as a validated PayloadA
func (p *ProcessPaymentBody_OneOf) AsValidatedPayloadA() (PayloadA, error) {
	val, err := p.AsPayloadA()
	if err != nil {
		var zero PayloadA
		return zero, err
	}
	if err := p.validatePayloadA(val); err != nil {
		var zero PayloadA
		return zero, err
	}
	return val, nil
}

// FromPayloadA overwrites any union data inside the ProcessPaymentBody_OneOf as the provided PayloadA
func (p *ProcessPaymentBody_OneOf) FromPayloadA(val PayloadA) error {
	// Validate before storing
	if err := p.validatePayloadA(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsPayloadB returns the union data inside the ProcessPaymentBody_OneOf as a PayloadB
func (p *ProcessPaymentBody_OneOf) AsPayloadB() (PayloadB, error) {
	return UnmarshalAs[PayloadB](p.union)
}

// AsValidatedPayloadB returns the union data inside the ProcessPaymentBody_OneOf as a validated PayloadB
func (p *ProcessPaymentBody_OneOf) AsValidatedPayloadB() (PayloadB, error) {
	val, err := p.AsPayloadB()
	if err != nil {
		var zero PayloadB
		return zero, err
	}
	if err := p.validatePayloadB(val); err != nil {
		var zero PayloadB
		return zero, err
	}
	return val, nil
}

// FromPayloadB overwrites any union data inside the ProcessPaymentBody_OneOf as the provided PayloadB
func (p *ProcessPaymentBody_OneOf) FromPayloadB(val PayloadB) error {
	// Validate before storing
	if err := p.validatePayloadB(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsPayloadC returns the union data inside the ProcessPaymentBody_OneOf as a PayloadC
func (p *ProcessPaymentBody_OneOf) AsPayloadC() (PayloadC, error) {
	return UnmarshalAs[PayloadC](p.union)
}

// AsValidatedPayloadC returns the union data inside the ProcessPaymentBody_OneOf as a validated PayloadC
func (p *ProcessPaymentBody_OneOf) AsValidatedPayloadC() (PayloadC, error) {
	val, err := p.AsPayloadC()
	if err != nil {
		var zero PayloadC
		return zero, err
	}
	if err := p.validatePayloadC(val); err != nil {
		var zero PayloadC
		return zero, err
	}
	return val, nil
}

// FromPayloadC overwrites any union data inside the ProcessPaymentBody_OneOf as the provided PayloadC
func (p *ProcessPaymentBody_OneOf) FromPayloadC(val PayloadC) error {
	// Validate before storing
	if err := p.validatePayloadC(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// validatePayloadA validates a PayloadA value
func (p *ProcessPaymentBody_OneOf) validatePayloadA(val PayloadA) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePayloadB validates a PayloadB value
func (p *ProcessPaymentBody_OneOf) validatePayloadB(val PayloadB) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePayloadC validates a PayloadC value
func (p *ProcessPaymentBody_OneOf) validatePayloadC(val PayloadC) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (p ProcessPaymentBody_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProcessPaymentBody_OneOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
