// Code generated by oapi-codegen. DO NOT EDIT.

package deeppathref

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	GetUser(ctx context.Context, options *GetUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetUserResponse, error)

	GetPost(ctx context.Context, options *GetPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetPostResponse, error)

	ListComments(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*ListCommentsResponse, error)

	CreateEvent(ctx context.Context, options *CreateEventRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateEventResponse, error)
}

func (c *Client) GetUser(ctx context.Context, options *GetUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetUserResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/users/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetUserResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetUserResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

func (c *Client) GetPost(ctx context.Context, options *GetPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetPostResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/posts/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetPostResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetPostResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/posts/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

func (c *Client) ListComments(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*ListCommentsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/comments",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListCommentsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListCommentsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/comments")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

func (c *Client) CreateEvent(ctx context.Context, options *CreateEventRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateEventResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/events",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateEventResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 201 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateEventResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/events")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// GetUserRequestOptions is the options needed to make a request to GetUser.
type GetUserRequestOptions struct {
	PathParams *GetUserPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetUserRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetUserRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetUserRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetUserRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetUserRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetPostRequestOptions is the options needed to make a request to GetPost.
type GetPostRequestOptions struct {
	PathParams *GetPostPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetPostRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetPostRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetPostRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetPostRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetPostRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateEventRequestOptions is the options needed to make a request to CreateEvent.
type CreateEventRequestOptions struct {
	Body *CreateEventBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateEventRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateEventRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *CreateEventRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateEventRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateEventRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

type GetUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetPostPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetPostPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type CreateEventBody struct {
	Name *string `json:"name,omitempty"`

	// Timestamp When the user was created
	Timestamp *Users_Get_Response200_JSON_Properties_CreatedAt `json:"timestamp,omitempty"`
	Metadata  *CreateEventBody_Metadata                        `json:"metadata,omitempty"`
}

func (c CreateEventBody) Validate() error {
	var errors runtime.ValidationErrors
	if c.Timestamp != nil {
		if v, ok := any(c.Timestamp).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Timestamp", err)
			}
		}
	}
	if c.Metadata != nil {
		if v, ok := any(c.Metadata).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Metadata", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetUserResponse struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`

	// CreatedAt When the user was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// UpdatedAt When the user was last updated
	UpdatedAt *time.Time                 `json:"updatedAt,omitempty"`
	Metadata  *GetUser_Response_Metadata `json:"metadata,omitempty"`
}

type GetPostResponse struct {
	ID      *string `json:"id,omitempty"`
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`

	// CreatedAt When the user was created
	CreatedAt *Users_Get_Response200_JSON_Properties_CreatedAt `json:"createdAt,omitempty"`

	// UpdatedAt When the user was last updated
	UpdatedAt *Users_Get_Response200_JSON_Properties_UpdatedAt `json:"updatedAt,omitempty"`
	Metadata  *GetPost_Response_Metadata                       `json:"metadata,omitempty"`
}

// Users_Get_Response200_JSON_Properties_CreatedAt When the user was created
type Users_Get_Response200_JSON_Properties_CreatedAt = time.Time

// Users_Get_Response200_JSON_Properties_UpdatedAt When the user was last updated
type Users_Get_Response200_JSON_Properties_UpdatedAt = time.Time

type ListCommentsResponse ListComments_Response

type CreateEventResponse struct {
	ID     *string `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
}

type GetUser_Response_Metadata struct {
	Tags  []string `json:"tags,omitempty"`
	Score *int     `json:"score,omitempty"`
}

type GetPost_Response_Metadata struct {
	Tags  []string `json:"tags,omitempty"`
	Score *int     `json:"score,omitempty"`
}

type ListComments_Response []ListComments_Response_Item

func (l ListComments_Response) Validate() error {
	if l == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range l {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ListComments_Response_Metadata struct {
	Tags  []string `json:"tags,omitempty"`
	Score *int     `json:"score,omitempty"`
}

type ListComments_Response_Item struct {
	ID   *string `json:"id,omitempty"`
	Text *string `json:"text,omitempty"`

	// CreatedAt When the user was created
	CreatedAt *Users_Get_Response200_JSON_Properties_CreatedAt `json:"createdAt,omitempty"`

	// UpdatedAt When the user was last updated
	UpdatedAt *Users_Get_Response200_JSON_Properties_UpdatedAt `json:"updatedAt,omitempty"`
	Metadata  *ListComments_Response_Metadata                  `json:"metadata,omitempty"`
}

func (l ListComments_Response_Item) Validate() error {
	var errors runtime.ValidationErrors
	if l.CreatedAt != nil {
		if v, ok := any(l.CreatedAt).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CreatedAt", err)
			}
		}
	}
	if l.UpdatedAt != nil {
		if v, ok := any(l.UpdatedAt).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("UpdatedAt", err)
			}
		}
	}
	if l.Metadata != nil {
		if v, ok := any(l.Metadata).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Metadata", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateEventBody_Metadata struct {
	Tags  []string `json:"tags,omitempty"`
	Score *int     `json:"score,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
