// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ClientAndMaybeIdentityType string

const (
	ClientAndMaybeIdentityTypeClient       ClientAndMaybeIdentityType = "client"
	ClientAndMaybeIdentityTypeClientWithID ClientAndMaybeIdentityType = "client-with-id"
	ClientAndMaybeIdentityTypeIdentity     ClientAndMaybeIdentityType = "identity"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Client struct {
	Name string `json:"name" validate:"required"`
}

func (c Client) Validate() error {
	return schemaTypesValidate.Struct(c)
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type ClientAndMaybeIdentity struct {
	Entity *ClientAndMaybeIdentityEntityAnyOf `json:"entity,omitempty"`
	Type   ClientAndMaybeIdentityType         `json:"type" validate:"required"`
}

func (c ClientAndMaybeIdentity) Validate() error {
	return schemaTypesValidate.Struct(c)
}

type ClientOrID = ClientOrIDOneOf

type ClientOrIdentityWithDiscriminator = ClientOrIdentityWithDiscriminatorOneOf

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type ClientAndMaybeIdentityEntityAnyOf struct {
	runtime.Either[Client, Identity]
}

func (c *ClientAndMaybeIdentityEntityAnyOf) MarshalJSON() ([]byte, error) {
	data := c.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (c *ClientAndMaybeIdentityEntityAnyOf) UnmarshalJSON(data []byte) error {
	return c.Unmarshal(data)
}

type ClientOrIDOneOf struct {
	runtime.Either[Client, string]
}

func (c *ClientOrIDOneOf) MarshalJSON() ([]byte, error) {
	data := c.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

func (c *ClientOrIDOneOf) UnmarshalJSON(data []byte) error {
	return c.Unmarshal(data)
}

type ClientOrIdentityWithDiscriminatorOneOf struct {
	runtime.Either[Client, Identity]
}

func (c ClientOrIdentityWithDiscriminatorOneOf) discriminator(data []byte) (string, error) {
	var discriminator struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return "", err
	}
	return discriminator.Value, nil
}

func (c *ClientOrIdentityWithDiscriminatorOneOf) MarshalJSON() ([]byte, error) {
	data := c.Value()
	if data == nil {
		return nil, nil
	}

	obj, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	disc, err := c.discriminator(obj)
	if err != nil {
		return nil, err
	}
	return marshalJSONWithDiscriminator(obj, "type", disc)
}

func (c *ClientOrIdentityWithDiscriminatorOneOf) UnmarshalJSON(data []byte) error {
	discriminator, err := c.discriminator(data)
	if err != nil {
		return err
	}

	switch discriminator {
	case "client":
		var res Client
		if err = json.Unmarshal(data, &res); err != nil {
			return err
		}

		c.A = res
		c.N = 1
	case "identity":
		var res Identity
		if err = json.Unmarshal(data, &res); err != nil {
			return err
		}

		c.B = res
		c.N = 2
	default:
		return errors.New("unknown discriminator value: " + discriminator)
	}
	return nil
}
