// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// ProductName The PayPal product for which the customer is onboarded.
type ProductName string

const (
	ADVANCEDVAULTING ProductName = "ADVANCED_VAULTING"
	EXPRESSCHECKOUT  ProductName = "EXPRESS_CHECKOUT"
	PAYMENTMETHODS   ProductName = "PAYMENT_METHODS"
	PPCP             ProductName = "PPCP"
	PPPLUS           ProductName = "PPPLUS"
	WPPRO            ProductName = "WP_PRO"
)

// Validate checks if the ProductName value is valid
func (p ProductName) Validate() error {
	switch p {
	case ADVANCEDVAULTING, EXPRESSCHECKOUT, PAYMENTMETHODS, PPCP, PPPLUS, WPPRO:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductName value, got: %v", p))
	}
}

// ProductName0 The name of the product.
type ProductName0 string

const (
	BILLMELATER                  ProductName0 = "BILL_ME_LATER"
	EBAYCHECKOUT                 ProductName0 = "EBAY_CHECKOUT"
	EMAILPAYMENTS                ProductName0 = "EMAIL_PAYMENTS"
	ENHANCEDRECURRINGPAYMENTS    ProductName0 = "ENHANCED_RECURRING_PAYMENTS"
	HOSTEDSOLESOLUTION           ProductName0 = "HOSTED_SOLE_SOLUTION"
	MASSPAYMENT                  ProductName0 = "MASS_PAYMENT"
	MOBILEEXPRESSCHECKOUT        ProductName0 = "MOBILE_EXPRESS_CHECKOUT"
	MOBILEINSTORE                ProductName0 = "MOBILE_IN_STORE"
	MOBILEPAYMENTACCEPTANCE      ProductName0 = "MOBILE_PAYMENT_ACCEPTANCE"
	MOBILEPAYPALSTANDARD         ProductName0 = "MOBILE_PAYPAL_STANDARD"
	PAYFLOWLINK                  ProductName0 = "PAYFLOW_LINK"
	PAYFLOWPRO                   ProductName0 = "PAYFLOW_PRO"
	PAYPALADVANCED               ProductName0 = "PAYPAL_ADVANCED"
	PAYPALHERE                   ProductName0 = "PAYPAL_HERE"
	PAYPALPRO                    ProductName0 = "PAYPAL_PRO"
	PAYPALSTANDARD               ProductName0 = "PAYPAL_STANDARD"
	PPCPCUSTOM                   ProductName0 = "PPCP_CUSTOM"
	PPCPSTANDARD                 ProductName0 = "PPCP_STANDARD"
	ProductName0ADVANCEDVAULTING ProductName0 = "ADVANCED_VAULTING"
	ProductName0EXPRESSCHECKOUT  ProductName0 = "EXPRESS_CHECKOUT"
	ProductName0PAYMENTMETHODS   ProductName0 = "PAYMENT_METHODS"
	VIRTUALTERMINAL              ProductName0 = "VIRTUAL_TERMINAL"
	WEBSITEPAYMENTSPRO20         ProductName0 = "WEBSITE_PAYMENTS_PRO_2_0"
	WEBSITEPAYMENTSPRO30         ProductName0 = "WEBSITE_PAYMENTS_PRO_3_0"
	WEBSITEPAYMENTSSTANDARD      ProductName0 = "WEBSITE_PAYMENTS_STANDARD"
)

// Validate checks if the ProductName0 value is valid
func (p ProductName0) Validate() error {
	switch p {
	case BILLMELATER, EBAYCHECKOUT, EMAILPAYMENTS, ENHANCEDRECURRINGPAYMENTS, HOSTEDSOLESOLUTION, MASSPAYMENT, MOBILEEXPRESSCHECKOUT, MOBILEINSTORE, MOBILEPAYMENTACCEPTANCE, MOBILEPAYPALSTANDARD, PAYFLOWLINK, PAYFLOWPRO, PAYPALADVANCED, PAYPALHERE, PAYPALPRO, PAYPALSTANDARD, PPCPCUSTOM, PPCPSTANDARD, ProductName0ADVANCEDVAULTING, ProductName0EXPRESSCHECKOUT, ProductName0PAYMENTMETHODS, VIRTUALTERMINAL, WEBSITEPAYMENTSPRO20, WEBSITEPAYMENTSPRO30, WEBSITEPAYMENTSSTANDARD:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductName0 value, got: %v", p))
	}
}

type ProductStatus string

const (
	ACTIVE   ProductStatus = "ACTIVE"
	INACTIVE ProductStatus = "INACTIVE"
	PENDING  ProductStatus = "PENDING"
)

// Validate checks if the ProductStatus value is valid
func (p ProductStatus) Validate() error {
	switch p {
	case ACTIVE, INACTIVE, PENDING:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductStatus value, got: %v", p))
	}
}

type GetReferralsResponse struct {
	Products []ProductName `json:"products,omitempty"`
}

type GetMerchantsResponse struct {
	Products []Product `json:"products,omitempty"`
}

type Product struct {
	// Name The name of the product.
	Name   *ProductName0  `json:"name,omitempty"`
	Status *ProductStatus `json:"status,omitempty"`
}

func (p Product) Validate() error {
	var errors runtime.ValidationErrors
	if p.Name != nil {
		if v, ok := any(p.Name).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Name", err)
			}
		}
	}
	if p.Status != nil {
		if v, ok := any(p.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
