// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type PostUsersBody = User

type GetUsersResponse = User

type PostUsersResponse = User

type User struct {
	Name    *string  `json:"name,omitempty"`
	Age     *int     `json:"age,omitempty"`
	Address *Address `json:"address,omitempty"`
	Contact *Contact `json:"contact,omitempty"`
	ID      *string  `json:"id,omitempty"`
}

func (u User) Validate() error {
	var errors runtime.ValidationErrors
	if u.Address != nil {
		if v, ok := any(u.Address).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Address", err)
			}
		}
	}
	if u.Contact != nil {
		if v, ok := any(u.Contact).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Contact", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Address struct {
	Street  *string `json:"street,omitempty"`
	City    *string `json:"city,omitempty"`
	ZipCode *string `json:"zipCode,omitempty"`
}

type Contact struct {
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
