// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash/oapi-codegen/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Order struct {
	Product *Order_Product1 `json:"product,omitempty"`
}

func (o Order) Validate() error {
	return schemaTypesValidate.Struct(o)
}

type Order_Product1 struct {
	Order_Product_AllOf0 *Order_Product_AllOf0 `json:"-"`
	Base                 Base                  `json:"-"`
}

func (o Order_Product1) Validate() error {
	return schemaTypesValidate.Struct(o)
}

func (o Order_Product1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Product_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Order_Product_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(o.Base)
		if err != nil {
			return nil, fmt.Errorf("Base marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Product1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Product_AllOf0 == nil {
		o.Order_Product_AllOf0 = &Order_Product_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Product_AllOf0); err != nil {
		return fmt.Errorf("Order_Product_AllOf0 unmarshal: %w", err)
	}

	if err := runtime.UnmarshalJSON(data, &o.Base); err != nil {
		return fmt.Errorf("Base unmarshal: %w", err)
	}

	return nil
}

type Base struct {
	Weight float32 `json:"weight" validate:"required"`
}

func (b Base) Validate() error {
	return schemaTypesValidate.Struct(b)
}

type VariantA struct {
	Color *string `json:"color,omitempty"`
}

func (v VariantA) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type VariantB struct {
	Country *string `json:"country,omitempty"`
}

func (v VariantB) Validate() error {
	return schemaTypesValidate.Struct(v)
}

type Order_Product struct {
	Order_Product_AllOf0 *Order_Product_AllOf0 `json:"-"`
	Base                 Base                  `json:"-"`
}

func (o Order_Product) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Product_AllOf0)
		if err != nil {
			return nil, fmt.Errorf("Order_Product_AllOf0 marshal: %w", err)
		}
		parts = append(parts, b)
	}

	{
		b, err := runtime.MarshalJSON(o.Base)
		if err != nil {
			return nil, fmt.Errorf("Base marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Product) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Product_AllOf0 == nil {
		o.Order_Product_AllOf0 = &Order_Product_AllOf0{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Product_AllOf0); err != nil {
		return fmt.Errorf("Order_Product_AllOf0 unmarshal: %w", err)
	}

	if err := runtime.UnmarshalJSON(data, &o.Base); err != nil {
		return fmt.Errorf("Base unmarshal: %w", err)
	}

	return nil
}

type Order_Product_AllOf0 struct {
	Order_Product_AllOf0_AnyOf *Order_Product_AllOf0_AnyOf `json:"-"`
}

func (o Order_Product_AllOf0) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(o.Order_Product_AllOf0_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Order_Product_AllOf0_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (o *Order_Product_AllOf0) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if o.Order_Product_AllOf0_AnyOf == nil {
		o.Order_Product_AllOf0_AnyOf = &Order_Product_AllOf0_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, o.Order_Product_AllOf0_AnyOf); err != nil {
		return fmt.Errorf("Order_Product_AllOf0_AnyOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Order_Product_AllOf0_AnyOf struct {
	runtime.Either[VariantA, VariantB]
}
