// Code generated by oapi-codegen. DO NOT EDIT.

package simple

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type PostUsersBody = User

type PostUsersResponse struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (p PostUsersResponse) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type User struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
