openapi: "3.0.0"
info:
  version: 1.0.0
  title: Property Filtering Example
  description: |
    This example demonstrates schema property filtering capabilities.

    Key scenarios tested:
    1. Basic property filtering - only specified properties are included
    2. Transitive pruning - schemas only referenced by filtered-out properties are removed
    3. Response type filtering - inline response types use filtered schemas
    4. Nested schema filtering - filtering works through $ref chains
    5. anyOf with schema refs - expandable fields (string | Object) are properly pruned
paths:
  /users:
    get:
      operationId: getUsers
      summary: List users
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      operationId: createUser
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Success - returns the created user
          content:
            application/json:
              # This response references User schema.
              # The generated inline response type should only have filtered properties.
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{id}:
    get:
      operationId: getUser
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
          description: Unique identifier
        email:
          type: string
          format: email
        name:
          type: string
        # These properties reference other schemas.
        # When filtered out, the referenced schemas should also be pruned
        # if they're not referenced elsewhere.
        profile:
          $ref: "#/components/schemas/Profile"
        settings:
          $ref: "#/components/schemas/Settings"
        # This references a schema that has its own nested references
        organization:
          $ref: "#/components/schemas/Organization"
        # Expandable field pattern (like Stripe uses)
        # Can be either a string ID or an expanded Manager object
        # When filtered out, Manager schema should be pruned
        manager:
          anyOf:
            - type: string
              maxLength: 255
            - $ref: "#/components/schemas/Manager"

    Profile:
      type: object
      description: |
        User profile information.
        This schema should be PRUNED when User.profile is filtered out.
      properties:
        bio:
          type: string
        avatar_url:
          type: string
        # References another schema - tests transitive pruning
        social_links:
          $ref: "#/components/schemas/SocialLinks"

    SocialLinks:
      type: object
      description: |
        Social media links.
        This schema should be PRUNED because it's only referenced by Profile,
        which is pruned when User.profile is filtered out.
      properties:
        twitter:
          type: string
        linkedin:
          type: string

    Settings:
      type: object
      description: |
        User settings.
        This schema should be PRUNED when User.settings is filtered out.
      properties:
        theme:
          type: string
          enum:
            - light
            - dark
        notifications:
          type: boolean

    Manager:
      type: object
      description: |
        Manager information (expandable field).
        This schema should be PRUNED when User.manager is filtered out,
        even though it's referenced via anyOf.
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        department:
          type: string

    Organization:
      type: object
      description: |
        Organization that a user belongs to.
        This schema is kept because User.organization is in the filter.
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        # This property references a schema that should be pruned
        # when Organization.billing is filtered out
        billing:
          $ref: "#/components/schemas/BillingInfo"
        # This property is kept
        plan:
          type: string
          enum:
            - free
            - pro
            - enterprise

    BillingInfo:
      type: object
      description: |
        Billing information.
        This schema should be PRUNED when Organization.billing is filtered out.
      properties:
        card_last4:
          type: string
        card_brand:
          type: string
        # References PaymentMethod - tests deep transitive pruning
        payment_method:
          $ref: "#/components/schemas/PaymentMethod"

    PaymentMethod:
      type: object
      description: |
        Payment method details.
        This schema should be PRUNED because it's only referenced by BillingInfo,
        which is pruned when Organization.billing is filtered out.
      properties:
        type:
          type: string
        details:
          type: object

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
