// Code generated by oapi-codegen. DO NOT EDIT.

package filteringbyproperty

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// GetUsers List users
	GetUsers(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetUsersResponse, error)

	// CreateUser Create a user
	CreateUser(ctx context.Context, options *CreateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateUserResponse, error)

	// GetUser Get a user by ID
	GetUser(ctx context.Context, options *GetUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetUserResponse, error)
}

// GetUsers List users
func (c *Client) GetUsers(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetUsersResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/users",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetUsersResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetUsersResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateUser Create a user
func (c *Client) CreateUser(ctx context.Context, options *CreateUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateUserResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/users",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateUserResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateUserErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateUserResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetUser Get a user by ID
func (c *Client) GetUser(ctx context.Context, options *GetUserRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetUserResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/users/{id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetUserResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetUserResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/users/{id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// CreateUserRequestOptions is the options needed to make a request to CreateUser.
type CreateUserRequestOptions struct {
	Body *CreateUserBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateUserRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateUserRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *CreateUserRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateUserRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateUserRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetUserRequestOptions is the options needed to make a request to GetUser.
type GetUserRequestOptions struct {
	PathParams *GetUserPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetUserRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetUserRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetUserRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetUserRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetUserRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

type OrganizationPlan string

const (
	Enterprise OrganizationPlan = "enterprise"
	Free       OrganizationPlan = "free"
	Pro        OrganizationPlan = "pro"
)

type GetUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type CreateUserBody = User

type GetUsersResponse []User

type CreateUserResponse = User

type CreateUserErrorResponse struct {
	Code    string  `json:"code" validate:"required"`
	Message string  `json:"message" validate:"required"`
	Details *string `json:"details,omitempty"`
}

func (r CreateUserErrorResponse) Error() string {
	res0 := r.Message
	return res0
}

type GetUserResponse = User

type User struct {
	// ID Unique identifier
	ID    string        `json:"id" validate:"required"`
	Email runtime.Email `json:"email" validate:"required"`
	Name  *string       `json:"name,omitempty"`

	// Organization Organization that a user belongs to.
	// This schema is kept because User.organization is in the filter.
	Organization *Organization `json:"organization,omitempty"`
}

func (u User) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

// Organization Organization that a user belongs to.
// This schema is kept because User.organization is in the filter.
type Organization struct {
	ID   string            `json:"id" validate:"required"`
	Name string            `json:"name" validate:"required"`
	Plan *OrganizationPlan `json:"plan,omitempty"`
}

func (o Organization) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(o))
}

type Error struct {
	Code    string  `json:"code" validate:"required"`
	Message string  `json:"message" validate:"required"`
	Details *string `json:"details,omitempty"`
}

func (e Error) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(e))
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
