// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type Order struct {
	Client *Order_Client `json:"client,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if o.Client != nil {
		if v, ok := any(o.Client).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Client", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Client struct {
	Name     string    `json:"name" validate:"required"`
	ID       *int      `json:"id,omitempty"`
	Identity *Identity `json:"identity,omitempty"`
	Address  *Address  `json:"address,omitempty"`
}

func (o Order_Client) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(o.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if o.Identity != nil {
		if v, ok := any(o.Identity).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Identity", err)
			}
		}
	}
	if o.Address != nil {
		if v, ok := any(o.Address).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Address", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Client struct {
	Name string `json:"name" validate:"required"`
}

func (c Client) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(i))
}

type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
