// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"encoding/json"
	"fmt"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

type ListNotificationsResponse []Notification

type Notification struct {
	Notification_AnyOf   *Notification_AnyOf `json:"-"`
	AdditionalProperties map[string]string   `json:"-"`
}

// Getter for additional properties for Notification. Returns the specified
// element and whether it was found
func (n Notification) Get(fieldName string) (value string, found bool) {
	if n.AdditionalProperties != nil {
		value, found = n.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Notification
func (n *Notification) Set(fieldName string, value string) {
	if n.AdditionalProperties == nil {
		n.AdditionalProperties = make(map[string]string)
	}
	n.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Notification to handle AdditionalProperties
func (n *Notification) UnmarshalJSON(data []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}

	if err := json.Unmarshal(data, &n.Notification_AnyOf); err != nil {
		return fmt.Errorf("error reading embedded 'Notification_AnyOf': %w", err)
	}
	delete(object, "email")
	delete(object, "subject")
	delete(object, "phone")
	delete(object, "device_token")
	delete(object, "badge")

	if len(object) != 0 {
		n.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			n.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Notification to handle AdditionalProperties
func (n Notification) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if n.Notification_AnyOf != nil {
		{
			embeddedJSON, err := json.Marshal(n.Notification_AnyOf)
			if err != nil {
				return nil, fmt.Errorf("error marshaling embedded 'Notification_AnyOf': %w", err)
			}
			var embeddedObj map[string]json.RawMessage
			if err := json.Unmarshal(embeddedJSON, &embeddedObj); err == nil {
				for k, v := range embeddedObj {
					object[k] = v
				}
			}
		}
	}

	for fieldName, field := range n.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

type EmailNotification struct {
	Email   string  `json:"email"`
	Subject *string `json:"subject,omitempty"`
}

type SMSNotification struct {
	Phone string `json:"phone"`
}

type PushNotification struct {
	DeviceToken string `json:"device_token"`
	Badge       *int   `json:"badge,omitempty"`
}

type Notification_AnyOf struct {
	union json.RawMessage
}

func (n *Notification_AnyOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the Notification_AnyOf as bytes
func (n *Notification_AnyOf) Raw() json.RawMessage {
	return n.union
}

// AsEmailNotification returns the union data inside the Notification_AnyOf as a EmailNotification
func (n *Notification_AnyOf) AsEmailNotification() (EmailNotification, error) {
	return runtime.UnmarshalAs[EmailNotification](n.union)
}

// AsValidatedEmailNotification returns the union data inside the Notification_AnyOf as a validated EmailNotification
func (n *Notification_AnyOf) AsValidatedEmailNotification() (EmailNotification, error) {
	val, err := n.AsEmailNotification()
	if err != nil {
		var zero EmailNotification
		return zero, err
	}
	if err := n.validateEmailNotification(val); err != nil {
		var zero EmailNotification
		return zero, err
	}
	return val, nil
}

// FromEmailNotification overwrites any union data inside the Notification_AnyOf as the provided EmailNotification
func (n *Notification_AnyOf) FromEmailNotification(val EmailNotification) error {
	// Validate before storing
	if err := n.validateEmailNotification(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsSMSNotification returns the union data inside the Notification_AnyOf as a SMSNotification
func (n *Notification_AnyOf) AsSMSNotification() (SMSNotification, error) {
	return runtime.UnmarshalAs[SMSNotification](n.union)
}

// AsValidatedSMSNotification returns the union data inside the Notification_AnyOf as a validated SMSNotification
func (n *Notification_AnyOf) AsValidatedSMSNotification() (SMSNotification, error) {
	val, err := n.AsSMSNotification()
	if err != nil {
		var zero SMSNotification
		return zero, err
	}
	if err := n.validateSMSNotification(val); err != nil {
		var zero SMSNotification
		return zero, err
	}
	return val, nil
}

// FromSMSNotification overwrites any union data inside the Notification_AnyOf as the provided SMSNotification
func (n *Notification_AnyOf) FromSMSNotification(val SMSNotification) error {
	// Validate before storing
	if err := n.validateSMSNotification(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsPushNotification returns the union data inside the Notification_AnyOf as a PushNotification
func (n *Notification_AnyOf) AsPushNotification() (PushNotification, error) {
	return runtime.UnmarshalAs[PushNotification](n.union)
}

// AsValidatedPushNotification returns the union data inside the Notification_AnyOf as a validated PushNotification
func (n *Notification_AnyOf) AsValidatedPushNotification() (PushNotification, error) {
	val, err := n.AsPushNotification()
	if err != nil {
		var zero PushNotification
		return zero, err
	}
	if err := n.validatePushNotification(val); err != nil {
		var zero PushNotification
		return zero, err
	}
	return val, nil
}

// FromPushNotification overwrites any union data inside the Notification_AnyOf as the provided PushNotification
func (n *Notification_AnyOf) FromPushNotification(val PushNotification) error {
	// Validate before storing
	if err := n.validatePushNotification(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// validateEmailNotification validates a EmailNotification value
func (n *Notification_AnyOf) validateEmailNotification(val EmailNotification) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateSMSNotification validates a SMSNotification value
func (n *Notification_AnyOf) validateSMSNotification(val SMSNotification) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePushNotification validates a PushNotification value
func (n *Notification_AnyOf) validatePushNotification(val PushNotification) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (n Notification_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := n.union.MarshalJSON()

	return bts, err
}

func (n *Notification_AnyOf) UnmarshalJSON(bts []byte) error {
	err := n.union.UnmarshalJSON(bts)

	return err
}
