// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
)

// GetClientRequestOptions is the options needed to make a request to GetClient.
type GetClientRequestOptions struct {
	Header *GetClientHeaders
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetClientRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Header != nil {
		if v, ok := any(o.Header).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Header", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetClientRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *GetClientRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetClientRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetClientRequestOptions) GetHeader() (map[string]string, error) {
	return runtime.AsMap[string](o.Header)
}

// UpdateClientRequestOptions is the options needed to make a request to UpdateClient.
type UpdateClientRequestOptions struct {
	Body   *UpdateClientBody
	Header *UpdateClientHeaders
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateClientRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}

	if o.Header != nil {
		if v, ok := any(o.Header).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Header", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateClientRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *UpdateClientRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateClientRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateClientRequestOptions) GetHeader() (map[string]string, error) {
	return runtime.AsMap[string](o.Header)
}
