// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/go-playground/validator/v10"
)

var headerTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type MSN = string

type GetClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

func (g GetClientHeaders) Validate() error {
	return headerTypesValidate.Struct(g)
}

type UpdateClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

func (u UpdateClientHeaders) Validate() error {
	return headerTypesValidate.Struct(u)
}
